dango_assistant_ghcr_user: ENC[AES256_GCM,data:S+Pl//o=,iv:nPXkWFB2gh4y2PebNzFc/zIBJ32d55Y7oIfwAG9tcP4=,tag:XScdWo4VU2o+MDsBFPoSOQ==,type:str]
dango_assistant_ghcr_token: ENC[AES256_GCM,data:Im9AcNbfuY8VkIAhWfbZKc+P/UqCwA3TXSFOvA1A/m9nxwdEWyDMng==,iv:lN7lxyaBt6KdbxFxawd6CYOWaTH3LrPFszPTkxEYB0k=,tag:sQjdT7eUtkp/FhJJ6RGCIA==,type:str]
dango_assistant_discord_token: ENC[AES256_GCM,data:tzmIA58GoltGKtoUD+iVwD5defg0SNFFS4L+F0DP+St7FFQhJLghzUg4K6AiAqU9SixAKLb7WVe4eaT58Ha1UsRbSAdV+pPX,iv:5oR2xQ0Z9t7qWNMEUnsE0+zsbWwcNMWpowW3H11ru1A=,tag:T6mn0pOmNK9fjoyRSnFZfA==,type:str]
dango_assistant_claude_oauth_token: ENC[AES256_GCM,data:S3Ft2DfwjoOv16RGnAw8Y+VKQh8omPPgVInT1dfsaUAs8xHQ/KhRTMeZnwB8woPjl12Rmg567Ogm8+WR0hRXa6fTSTy3js25NGH8yNagPwCjLt93sBjQYkjei1cvOEm6GdKe9T0VOufbyV/t,iv:UAflwqLWqey4o1NWA/xH3BRNPcfdgxJYAc0PoDTt8rk=,tag:SH1n8i37GKDSN0mMeGw60w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDYvN212ZyBBNXF3eUpq
        ZGlFU3lBakZPLy9xOVNiOTNoQVZVeHU2bFVmaS9pR2d1cVg1eQpidFlQc0FTT2RJ
        TjNkclpmRG9NSTdjb1RyNHpQcXpiMDZVNEpLTHRGOGNzCi0tLSA0NDh5WjU5ODFG
        ZVFNcElXbFBIZ21vRlQ2dTdHakUxcFB3Y0dQb0ZsWmh3ClrLLHSk3XAheQs0KIPd
        jiwZspKBqFhEwokiDqnE2n1Umm9FXl/YYoxazOSPhp4lzA2rWqEqN0A//bEMDmE0
        1No=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1q2jpj60frm2eh0lndcqf8he649yrmtp9z5n5l4l8e5rhmpncck03vsjwh62
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHdveEF2ZyBBNlFUc2hD
        aTBQYVJPNGhZYjM4N2t6d0wwTWFKUTEwMkNaR3BYVHpSRlpoSApHYStDdXl6Qk80
        RGtFSHN5ZnJLY1V5ckFSUm5UTXpkTGY2ZzBLeUxXUWJZCi0tLSBTOGpYUHJ1YnQz
        WS81ekFnQTFqTWtCMEhrTW9zSjJXNERiYkpRci8wckc0CnVsu19bGm2folAJ0tKW
        KPnf2p01voknWEKIycjpOl1HcYQ4ArUQDKcwvKMfmElH58baUbw4Efe/C+M8nnqM
        J+c=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1qdvpvuaxnxxrhdghjzmcm2m69w6f480h9wwt8g2900mu8pm2npn32hwdz5x
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHRXNW42USBBbjA2V1RE
        cWJoZ1ZVV3dqckhwUkJiblFyN3B3NEt1RjZYL21YVVNnMEYvNgp3NnlqSEllNzBG
        OGNhVTREaDB5alNyZFgxSkE3ZWRvaFoxeG9LRXRnU1NnCi0tLSBMTGFGWnYwb3ZR
        QlZVUklSK3dhUUo4R280RlZhcGc3SlBHMXRYMXluKzJFCnDznfQMXwrv7HsO0vCp
        ysv6/60hN5WlIBNxQglCplK5KDzlqTijDU8OFFtGDeMMOIFmi1PJG3DKEswUVtvk
        GIg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1qtwrakqqgzc4pue7fg5xp2d6vnna8xvd7vh7vtzvk37jvcc8zawnjvzcyce
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEM5Q3NVZyBBeVNjS2pV
        T0ZHQnE0ajVzTUt3bjd3ZDdnaThyeUVqN3RKbUNHSjdHd2l0VApDdVF0UTR5bHJj
        TDlBSVFXWEd1WDZYeUR3SVlBcVI2cTlqb3BmcDlrZDdNCi0tLSBPVmlpV2RWVlAr
        VEtqbFN4eFQyODNvV2x6bm1heWZqOXpTMmRGTDAyWTVzClRxS2G4R8DM7V5FC8ZP
        emxOT/CO2I0v3BMOnOAEZMyqqD2pi/gOWcvWLjDHHVSUD2gR7Bd65uazWFviaD4a
        VyU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1q2ltwfyvzecj9nfr862nql2z67rwejwr6rjnzn8aspc8la3ax5gkkn5upmh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEEyT3d4USBBMXh2L2ZY
        K0NLb3paODMvQjh2NkZYVHZZRkFlVHBCSWpZVnJwLytpNE1lUgorL2U4MCtXYWF6
        Z2pSczlFdVNXdjFoRmtvNlF3c2JrODJvditiNzJNaFpNCi0tLSBnZDYxQWVqTTV4
        TldxV00ycHY2dW5LNjMxelpNdFpGa3lzNjNVRjNDTTlJCreaUg5clB9ittA4QqoD
        haXBxFT5h+TBs2amWIl3gIEWXqUMr6BqpMGE+sYk2YoS97fDnEJqawJQBZFDpwO2
        BBk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1qg8wygtvmr5hyx5njmpar8n35xjcvsh29dzug989hmyn3vd7atj85rft8d0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9DTjRkdyBBdWJqdWZo
        eWgraHU1MjUrcEdrN3IvVlZxcUdwdG1KaG5hRjJZSEM5L2lNYQpWRUlSMlRRdVRy
        bkF2NjBQSUQrZGl2bWtZMnBtVkczVTc5MFNFa1ZsRTFBCi0tLSBmemRxM1MxUzNw
        RlZNMVJLUUJ2QTRobnk1Zktnc3YzQUF5YzhSRHFKdGRFCtcwf35iBAEp/oeZT1Od
        7i/9ihGKAkk4KPlioGUxfz2nE0VaW3FLdmh/6ezA0QpnyG/hfFXvVBhj+T8F8h+c
        VHk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1q2y2eshvcqgyuuxd8kch54mdhf96znghyf99rd3yxqcrw4g5l9vpcs03x5h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZjM2VkdLSGlDRWFlMjlr
        Y2p1TXF3RjZYQ0RjTEhHVkVwRmNhQ3hGdG1jCm5OVk9hcnMrNFVKVWJEdDNZc2Y1
        Mkc0SjJjazFTRHhqN3ZlUUVDd1g2MkUKLS0tIHpQbTFjdks5N3lrZnZFZS9UUjhH
        b2NiQjFRbjhjQjhLdlN5SG1JR003eVkKLmpSu/UvjDYGaj+YPpqF+rJwe8jrQz4w
        gARHHRgQQaLJoJmNpFgL8O7pKdeA5QiEn89UywwB/I4LTs8ZrKeyGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10xqeelr09uk292rrp48jw5fem7uepuf82ax6mpq6rjuv6m3aw9mqgjnfyh
  lastmodified: "2026-06-15T23:35:02Z"
  mac: ENC[AES256_GCM,data:McDeogWLRLaqELIDkBts/dmdQR7LIaqo+UuHdGwhSGjhXqArLKv+SF4+t/gRE4Acm3zLhFf7sKJNErJDPvtAus05k6eRuXm6Jrf3qY3scAQ9zhION87rNOpFrmdcdA8dgSyDL5Y5D4d6Xp/CFRovy3GK6fXG/ofqvcNmPeFzv6Y=,iv:Pqza+vXUnxtyyyqHXVhruuL9rJXtJ3VWQLW2mI0DPpc=,tag:qn9Vrmxq+19tzfkas+tb7A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
