// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addr } from "./Addr";
import type { Duration } from "./Duration";
import type { Permissions } from "./Permissions";

/**
 * Set of updates to be made to the config.
 *
 * A field being `Some` means it is to be updated to be the given value;
 * it being `None` means it is not to be updated.
 */
export type ConfigUpdates = { owner: Addr | null, bank: Addr | null, taxman: Addr | null, cronjobs: { [key: Addr]: Duration } | null, permissions: Permissions | null, };
