// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A span of time, in nanosecond precision.
 *
 * We can't use [`std::time::Duration`](std::time::Duration) because it doesn't
 * implement the Borsh traits. Additionally, it's serialized to JSON as a
 * struct, e.g. `{"seconds":123,"nanos":123}`, which isn't desirable.
 */
export type Duration = string;
