// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addr } from "./Addr";
import type { Binary } from "./Binary";
import type { Coins } from "./Coins";
import type { ConfigUpdates } from "./ConfigUpdates";

export type Message = { "configure": { updates: ConfigUpdates, app_updates: Record<string, any>, } } | { "transfer": { to: Addr, coins: Coins, } } | { "upload": { code: Binary, } } | { "instantiate": { code_hash: string, msg: Record<string, any>, salt: Binary, funds: Coins, admin: Addr | null, } } | { "execute": { contract: Addr, msg: Record<string, any>, funds: Coins, } } | { "migrate": { contract: Addr, new_code_hash: string, msg: Record<string, any>, } };
