// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addr } from "./Addr";

export type Permission = "Nobody" | "Everybody" | { "Somebodies": Array<Addr> };
