// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addr } from "./Addr";
import type { Message } from "./Message";

export type Tx = { sender: Addr, gas_limit: bigint, msgs: Array<Message>, data: Record<string, any>, credential: Record<string, any>, };
