// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addr } from "./Addr";
import type { Message } from "./Message";

/**
 * A transaction but without a gas limit or credential.
 *
 * This is for using in gas simulation.
 */
export type UnsignedTx = { sender: Addr, msgs: Array<Message>, };
