# https://rust-lang.github.io/rustfmt/
match_block_trailing_comma     = true
single_line_if_else_max_width  = 0
single_line_let_else_max_width = 0
style_edition                  = "2024"
use_field_init_shorthand       = true
use_try_shorthand              = true

# The following options are nightly-only. They are commented out because we
# format with the stable toolchain; uncomment when any one of them becomes
# available in stable.

# condense_wildcard_suffixes = true
# format_macro_bodies        = false
# format_macro_matchers      = false
# group_imports              = "Preserve"
# imports_granularity        = "One"
# normalize_comments         = true
# normalize_doc_attributes   = true
# overflow_delimited_expr    = true
# reorder_impl_items         = true
