//! Projection model for the historical indexer.
//!
//! A projection is a self-contained consumer of the block stream: it owns
//! its tables (and the migrations that create them) and stages writes one
//! block at a time into a [`Ctx`]. Tracking progress and committing are
//! deliberately NOT a projection's job: the app's [`Committer`] owns the
//! cursor table and drives the commit protocol (ClickHouse flush + ack
//! first, then the Postgres transaction carrying domain writes + cursor).
//!
//! Concrete projections live in this crate, one folder each: `entity/`
//! (sea-orm types generated by sea-orm-cli), `idens.rs` (definitions for
//! the migrations), one file per migration, and the `Projection` impl.
//!
//! See `DESIGN.md` § Commit protocol and § Schema migrations for the
//! full contract.

mod activity;
mod committer;
mod ctx;
mod projection;

pub use {
    activity::{ActivityConfig, ActivityProjection, ActivityQuery, EventType},
    committer::Committer,
    ctx::{ChWrite, Ctx},
    projection::Projection,
};
