use {
    crate::Ctx,
    actix_web::Scope,
    async_trait::async_trait,
    dango_indexer_historical_types::{AnyResult, BlockData},
    sea_orm_migration::MigrationTrait,
    std::num::NonZero,
};

/// Domain-specific consumer of the block stream.
///
/// Implementations own their tables and the migrations that create them;
/// cursors live in the committer's Postgres, and commits happen in the
/// committer after `process` returns. The app's `projection_loop` drives
/// one projection at a time, alternating between pull catch-up via
/// `BlockSource::get` and push live via the broadcast channel.
///
/// Each concrete projection lives in its own folder inside this crate:
/// `entity/` (sea-orm types generated by sea-orm-cli, used for queries),
/// `idens.rs` (identifier definitions for the migrations), and one file
/// per migration.
#[async_trait]
pub trait Projection: Send + Sync {
    /// Stable id keying this projection's cursor row and its ClickHouse
    /// deduplication tokens.
    ///
    /// Bumping the id forces a full re-backfill: a new id has no cursor
    /// row, so the projection catches up from `min_height()`.
    fn id(&self) -> &'static str;

    /// Minimum height this projection starts at; blocks below it are skipped
    /// (e.g. a contract that didn't exist before that block).
    ///
    /// `NonZero` by type: block 0 does not exist — the chain's first block is
    /// height 1 — so a projection can never declare it. The default is that
    /// genesis floor, [`NonZero::<u64>::MIN`].
    fn min_height(&self) -> NonZero<u64> {
        NonZero::<u64>::MIN
    }

    /// Schema migrations for this projection's Postgres tables.
    ///
    /// Declared on the trait so that what runs is derived from the
    /// projections actually registered in the app — there is no
    /// separate hardcoded list that could drift out of sync. Executed
    /// by the committer under one shared history; because the history
    /// is shared, migration file names must be unique across the app —
    /// include the projection name in the file name. The default has
    /// none.
    fn migrations(&self) -> Vec<Box<dyn MigrationTrait>> {
        vec![]
    }

    /// Idempotent DDL for this projection's ClickHouse tables
    /// (`CREATE TABLE IF NOT EXISTS ...
    /// SETTINGS non_replicated_deduplication_window = N`), following the
    /// existing `indexer/clickhouse` pattern. Run by the committer at
    /// boot, after the Postgres migrations; CH has no migration
    /// framework, so there is no tracking — statements must be safe to
    /// re-run. The default has none.
    fn ch_migrations(&self) -> Vec<String> {
        vec![]
    }

    /// Stage one block's writes into `ctx`.
    ///
    /// Postgres writes commit atomically with the cursor update;
    /// ClickHouse writes are flushed (and acknowledged) before that
    /// transaction commits. On ClickHouse the execution model is
    /// at-least-once: after a crash, `process` may run again for a block
    /// whose inserts already landed, and the dedup token turns the
    /// replayed insert into a no-op — therefore CH writes must not do
    /// cross-block read-modify-write against this projection's own
    /// unflushed output.
    ///
    /// Never commits: committing consumes the [`Ctx`], which this method
    /// only borrows.
    async fn process(&self, ctx: &mut Ctx, block: &BlockData) -> AnyResult<()>;

    /// The projection's read surface, as actix [`Scope`]s the app collects and
    /// mounts on the shared httpd — one per resource, each grouping its feeds
    /// under its prefix, exactly like the in-process indexer's
    /// `routes::blocks::services()`.
    ///
    /// A projection owns both its tables and the read surface over them, so the
    /// queries that expose its data live here, next to the schema that backs
    /// them. The handlers a scope mounts read the shared Postgres pool and block
    /// source from actix app data; they never need the projection instance, so a
    /// scope carries no state and is cheap to rebuild per worker. The default is
    /// none — a write-only (or not-yet-served) projection contributes no routes.
    fn services(&self) -> Vec<Scope> {
        vec![]
    }
}
