---
points_bot_dir: "{{ deploy_home }}/points-bot"
points_bot_image: "ghcr.io/left-curve/bots/points"
points_bot_tag: "2e2f1b64a3c28f0810f8611ac815693621c988a1"
points_bot_networks: []
points_bot_metrics_ports:
  devnet: 9300
  testnet: 9301
  mainnet: 9302
