---
- name: Set perp-liquidator instance index
  set_fact:
    perp_liquidator_instance_index: >-
      {{ (groups['perp-liquidator-' ~ dango_network] | default([])).index(inventory_hostname) }}
  when: inventory_hostname in (groups['perp-liquidator-' ~ dango_network] | default([]))

- name: Create perp-liquidator config directory
  file:
    path: "{{ deployment_dir }}/perp-liquidator"
    state: directory
    mode: '0755'
  when: perp_liquidator_instance_index is defined

- name: Template perp-liquidator .env
  template:
    src: perp-liquidator.env.j2
    dest: "{{ deployment_dir }}/perp-liquidator/.env"
    mode: '0600'
  when: perp_liquidator_instance_index is defined
