---
- name: Create perp-liquidator config directory
  file:
    path: "{{ deployment_dir }}/perp-liquidator"
    state: directory
    mode: '0755'
  when: inventory_hostname == perp_liquidator_host

- name: Template perp-liquidator .env
  template:
    src: perp-liquidator.env.j2
    dest: "{{ deployment_dir }}/perp-liquidator/.env"
    mode: '0600'
  when: inventory_hostname == perp_liquidator_host
