use grug::{Addr, Bound, Bounded, Bounds, Coin, NonZero, NumberConst, Udec256};

/// Defines the bounds for a fee rate: 0 <= FeeRate < 1.
#[grug::derive(Serde)]
pub struct FeeRateBounds;

impl Bounds<Udec256> for FeeRateBounds {
    const MAX: Option<Bound<Udec256>> = Some(Bound::Exclusive(Udec256::ONE));
    const MIN: Option<Bound<Udec256>> = None;
}

/// A decimal bounded by the fee rate bounds.
pub type FeeRate = Bounded<Udec256, FeeRateBounds>;

/// Global configuration of the AMM.
#[grug::derive(Serde, Borsh)]
pub struct Config {
    /// An account to receive the fees generated by the AMM.
    pub fee_recipient: Addr,
    /// The amount of fee that must be paid in order to create a pool.
    ///
    /// For reference, on Osmosis this is currently set to 20 OSMO or ~$10,
    /// which can be queried by:
    ///
    /// ```sh
    /// osmosisd q poolmanager params --node https://rpc.osmosis.zone:443
    /// ```
    pub pool_creation_fee: NonZero<Coin>,
    /// Percentage of the final swap output that is charged as protocol fee,
    /// paid to token stakers.
    ///
    /// Note to be confused with the liquidity fee, which is configured on a
    /// per-pool basis, and paid to liquidity providers.
    pub protocol_fee_rate: FeeRate,
}
