perps_bot_ghcr_user: ENC[AES256_GCM,data:R+cIztY=,iv:ylQ2V/c8Wu4G68Q9fyWtnT2QtKWa22pkcobQiEdOrC0=,tag:MGWCvrZYUwvI10iZ4Xx9Qg==,type:str]
perps_bot_ghcr_token: ENC[AES256_GCM,data:XimcVwKJzs/tMHE3lZIqXtRnL0P+dIZKyko8/PacZvcQk5nVWJ+3xw==,iv:ifmvNKlEd5SLRf8vpNWfG5XC56w+m97sJEQatT0zNYg=,tag:aGI76FWd9iyfradlms3jxw==,type:str]
perps_bot_private_key: ENC[AES256_GCM,data:LrvEGQw4TToH/cdU0IXK0WjsvYFe851Vu0r1VdDmKfzssT+pDpZNs5cpzOzpMCzT8NhapqnnP87yPs7wFIy6ww==,iv:hrdljrnl+tTINs5VYoqFsIAQYtkaM7/qbrjAqKaT7Y0=,tag:cwRZq5YMKERy5v5mElV3gg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDYvN212ZyBBcUMxRUd1
        cURRdWViN1g0YXd0cGY2RkkxQVdWYVZpNlQ0amx2cExpbFpORQppbkJYV3ZuU0hF
        N1NPT011V1RGYjIrYlZHMFBtL3lBQk1lVTNuWUtaZ3YwCi0tLSB5Umw3bkhaeU9Y
        TzFPZURqSlBlWlJiYldTVHFDZVFzTUlVMWtNMkwzeDNVCp913ZZ468dhi2HTotA2
        rrGooqk/iVXgPDsiynI0gDOVgRIUUW7kOA/cCTBoheA/PvsBAe/7PgcvJU2Qc1Qm
        e30=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1q2jpj60frm2eh0lndcqf8he649yrmtp9z5n5l4l8e5rhmpncck03vsjwh62
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHdveEF2ZyBBaVhXem8w
        alJpZDFHaklCN3hJRVBMWUlUcHNlaXF2aFpjYitURCsxL0xGYwp5bnNTNkVYQzNv
        SEVwUTQ0NUMwcklpbmtPT1VIanhQd3h3VXcwVnBqU0JvCi0tLSBRcVBhREpVMFNr
        eTRSTzErK01RUDJXRzhNTG5ReDhyZ0RQQ3c2aG9JMWY4CsVyspXFepXV5VNUXpB6
        BoNZjeKlb2FQVoYvHo2BCXxTIs4MQGNQu7Vnj2wyQclwRGR4eauyKPwF+Q/MzuUb
        aKI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1qdvpvuaxnxxrhdghjzmcm2m69w6f480h9wwt8g2900mu8pm2npn32hwdz5x
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHRXNW42USBBbVF1bWVa
        eWVlK0c0b01ySGE3VSthWmN1Mjk2KzNsR3VvdU55Y1puRmJxMwoxbFFkTkJGazJ1
        SVhnUjZhOW9YemY3QXRyZWI3TlBBRDZxU1FEV1g2UU44Ci0tLSByalhLamFXWUxT
        QjdmazZDZVBTQThiM0pUMnFQa05GSEhxSjdTZkhCZFY0CkPGPfZpiZPzHO6b95hU
        fa+wXjOTTgNk+T//D5/jRqAvf9+Y/I8HhEdtWpiO1t7r3vb7gILHsS10SsLuN0qS
        dnk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1qtwrakqqgzc4pue7fg5xp2d6vnna8xvd7vh7vtzvk37jvcc8zawnjvzcyce
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEM5Q3NVZyBBai8xbXRO
        WHkwU3k1YUdRNldYR1pFMTFHS3dmN3ZZd1NYRUttT2kzK1Z5UQpHeDg0YlVKYkRH
        WUhnWnZrQVZEWk9WTFR3UnU5ZVJpdEdqY0J1VVdrWWtrCi0tLSAxOWxzOTUwTnlo
        TjQ1Wjk2Q1JTeUdiWS9EV1NSSk9LS0FZWVRQYXRJaDlnCuP7ZJaJttAQgXdqg6ko
        /u3XXRvnyxCEExJS13ibHi0aFRwzFXDv7lVasQ4U09NQYNIu+MvFSDoahN68F3xQ
        oHs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1q2ltwfyvzecj9nfr862nql2z67rwejwr6rjnzn8aspc8la3ax5gkkn5upmh
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEEyT3d4USBBK2hYaHpl
        c2pyeXRFTkMyVmNkNDROdUxDQ3Y2L3ZnNXpXNk8reStHS2h2cQpXdGsxSnFNeUU5
        QTZ1MllKR3U1R20xOHYvWTBBemwwSFMyYm9rcW9LdWFvCi0tLSAvYjhzL1NlL2dn
        Wkp6TjNKZGVwVTFScXdEVlczVzFmYVFZVnN4Sis2NlY0Ck9wasBCxTfgfu7O90rv
        JRvwrxLsnIHE8jtg/o5d1BZ4fqbaMrcFOcV034xA+Bl8ycI9GaRErHBK7BBvr/jM
        sAk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1qg8wygtvmr5hyx5njmpar8n35xjcvsh29dzug989hmyn3vd7atj85rft8d0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9DTjRkdyBBbXJoalJi
        eklvTy9zaDZxVDFkWnRZQnZyUGh5QWpxbnpPendUZlN4MzdPRwpFWFpMZG9yMnUx
        a3p5Z1dxTURncHJ0c0Z1ZmJLM1R0cUM0Y2VuZXdyRkVRCi0tLSBNRU83NHVPOXpH
        MU52K2ZkZHU2WVRNS0xXSy9ZQVJ0WG9IeHJ0UHk5Vm0wCiOeVzKYq5GOm7tK7Jme
        ZvmatzxAnFLkUtlIRPQCzJ0V2vF+1qfOAH90rT0vO93LKJa1Mqb+u5eaJIVHnlOf
        cGs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yubikey1q2y2eshvcqgyuuxd8kch54mdhf96znghyf99rd3yxqcrw4g5l9vpcs03x5h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxajFudkd0Y0tSMFlsSnFp
        ZzcxM3pMcXZQSGxsb2lTVU05bGJYRHk4SjFrCis0UjQ5a2l0bnNYcWVsNG0yZjFX
        U244Zk1GTHFoZ1lYTTI5b3BTU20wUFkKLS0tICthNHdsZVZ0ZkJvZlBXd0N4S1pT
        cDE4OGRuMVZFMDAxMDFlZmdFS2ZpaGcK40DJvslw4mOw5KgX5VS6efXWHisRHi+y
        KfASqOTkgLe6Khmz2R29K5WxGPwhyr0Smvv1WQv2OnFGAxIVH3oBuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10xqeelr09uk292rrp48jw5fem7uepuf82ax6mpq6rjuv6m3aw9mqgjnfyh
  lastmodified: "2026-06-15T23:35:03Z"
  mac: ENC[AES256_GCM,data:MSx1Y0tGcq5bhHric3qrzpVKnkymt5Qqj9r3AUhrgCHOxSlR9lmcaPDTzv7fpabFJOCJ+S6MWDv8tW+NgGis/EGqodHxk2tZDbXM9ZQqdh2OabgxJiMWFD/tePqVPm+wodgsg3+XzxYDwg7Zs/88dO/OzM/QID183DQTo/CNTe0=,iv:IivpsTb1SsKXc24UcbOde3GPgoTH0NP3+jQfUQZ16xM=,tag:jDr+2eoXSiyKZZqVdg3TUA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
