set positional-arguments

# List available recipes
default:
  @just --list

# Create the development indexer database
create_dev_db:
  createdb -h localhost -U postgres grug_dev

# Run the development database
run_dev_db:
  docker compose up db

# Migrate the development database
# DATABASE_URL=postgres://postgres@localhost/grug_dev
migrate_dev_db:
  sea-orm-cli migrate up -d sql-migration

# Reset the development database
refresh_dev_db:
  sea-orm-cli migrate refresh

# Generate entity from the datatabase
generate_entity:
  sea-orm-cli generate entity -o sql/src/entity --model-extra-derives 'Default' --ignore-tables 'transfers'
