/**
 * Referral types for the taxman contract (PR #1563)
 * These types match the Rust types from dango/types/src/taxman.rs
 */

/**
 * Cumulative referral data for a user (as referrer)
 * Returned by the `ReferralData` query
 */
export type UserReferralData = {
  /** Cumulative volume of all referees */
  volume: string;
  /** Total commission earned from referees */
  commission: string;
  /** Number of active referees */
  active_referees: number;
};

/**
 * Statistics for an individual referee
 * Returned by the `ReferrerToRefereeStats` query
 */
export type RefereeStats = {
  /** The referee's user index */
  user_index: number;
  /** Timestamp when the referee registered */
  registered_at: number;
  /** Referee's total trading volume */
  volume: string;
  /** Commission generated by this referee */
  commission: string;
};

/**
 * Referrer's current settings
 * Returned by the `ReferralSettings` query
 */
export type ReferralSettings = {
  /** Commission rebound rate based on tier (e.g., "0.2" for 20%) */
  commission_rebound: string;
  /** Share ratio - how much the referrer shares with referee (e.g., "0.05" for 5%) */
  share_ratio: string;
};

/**
 * System-wide referral configuration
 * Returned by the taxman config query
 */
export type ReferralConfig = {
  /** Default commission rebound for new referrers (e.g., "0.1" for 10%) */
  default_commission_rebound: string;
  /** Volume-based tiers with progressive commission rates */
  tiers: Array<{
    /** Minimum volume to qualify for this tier (in USDC microunits) */
    min_volume: string;
    /** Commission rebound rate for this tier */
    commission_rebound: string;
  }>;
  /** Maximum share ratio a referrer can set */
  max_share_ratio: string;
};

/**
 * Order options for referee stats query
 */
export type RefereeStatsOrderBy = "volume" | "registered_at" | "commission";
