---
- hosts: historical-indexer
  become: true
  become_user: "{{ deploy_user }}"
  remote_user: deploy
  collections:
    - community.docker
  pre_tasks:
    - name: Get deploy user info
      getent:
        database: passwd
        key: "{{ deploy_user }}"
    - name: Set deploy_home fact
      set_fact:
        deploy_home: "{{ ansible_facts.getent_passwd[deploy_user][4] }}"
  tasks:
    - name: Drop historical-indexer instance databases
      include_role:
        name: historical-indexer
        tasks_from: drop-db-instance.yml
      loop: "{{ historical_indexer_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"
