set positional-arguments

# List available recipes
default:
  @just --list

provision:
  ansible-playbook -i inventory playbook.yml


# Set up Python environment and install Ansible + role
setup:
    python3 -m venv .venv
    source .venv/bin/activate && pip install --upgrade pip
    source .venv/bin/activate && pip install ansible
    source .venv/bin/activate && ansible-galaxy install MonolithProjects.github_actions_runner

# Run the runner installation playbook
install-runners:
    source .venv/bin/activate && ansible-playbook -i hosts setup-host.yml
    source .venv/bin/activate && ansible-playbook -i hosts install-runners.yml
