set positional-arguments

# List available recipes
default:
  @just --list

provision:
  ansible-playbook -i inventory playbook.yml


# Set up Python environment and install Ansible + role
setup:
    python3 -m venv .venv
    source .venv/bin/activate && pip install --upgrade pip
    source .venv/bin/activate && pip install ansible
    source .venv/bin/activate && ansible-galaxy install MonolithProjects.github_actions_runner
    source .venv/bin/activate && ansible-galaxy collection install community.docker

# Run the github runner installation playbooks
install-runners:
    source .venv/bin/activate && ansible-playbook -i inventory setup-github-runner-hosts.yml
    source .venv/bin/activate && ansible-playbook -i inventory install-github-runner-hosts.yml
