- hosts: all
  become: true
  remote_user: debian
  gather_facts: false
  vars:
    tailscale_args: "--accept-dns=false"
  pre_tasks:
    - ansible.builtin.import_tasks: tasks/load-debian-root-secrets.yml
  roles:
    - role: artis3n.tailscale.machine
