- hosts: vaultwarden
  become: true
  become_user: "{{ deploy_user }}"
  remote_user: debian
  gather_facts: false
  collections:
    - community.docker
  pre_tasks:
    - ansible.builtin.import_tasks: tasks/load-debian-root-secrets.yml

    - name: Get deploy user info
      getent:
        database: passwd
        key: "{{ deploy_user }}"

    - name: Set deploy_home fact
      set_fact:
        deploy_home: "{{ ansible_facts.getent_passwd[deploy_user][4] }}"
  roles:
    - vaultwarden
