import tailwindScrollbar from "tailwind-scrollbar";
import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";
export const tailwindConfig: Partial<Config> = {
  theme: {
    colors: {
      transparent: "transparent",
      status: {
        success: "#25B12A",
      },
      black: {
        DEFAULT: "#000000",
      },
      gray: {
        25: "#FAFAFA",
        50: "#F5F4F4",
        100: "#EAE9E9",
        200: "#D6D4D3",
        300: "#ACA9A7",
        400: "#837D7B",
        500: "#6E6865",
        600: "#59524F",
        700: "#463D39",
        800: "#302723",
        900: "#2E2421",
      },
      white: {
        DEFAULT: "#FFFFFF",
        100: "#FFFCF6",
        200: "#FFFBF0",
        300: "#FFF9E5",
        400: "#FFF3CC",
      },
      rice: {
        25: "#FFF9F0",
        50: "#FFF3E1",
        100: "#F2E2B8",
        200: "#EDD69A",
        300: "#E3BD66",
        400: "#DCA543",
        500: "#D4882C",
        600: "#BB6A24",
        700: "#9C4D21",
        800: "#7F3E21",
        900: "#69331E",
        950: "#3C190C",
      },
      brown: {
        50: "#F5F4F1",
        100: "#E6E4DB",
        200: "#CFC9B9",
        300: "#B3AA91",
        400: "#9D8F72",
        500: "#8E7F64",
        600: "#7A6954",
        700: "#625346",
        800: "#55473E",
        900: "#4A3F39",
        950: "#302723",
      },
      blue: {
        50: "#F7F8FB",
        100: "#F0F1F7",
        200: "#E2E3F2",
        300: "#CBCBE7",
        400: "#A9A8D5",
        500: "#918CC6",
        600: "#7B71B6",
        700: "#6A5FA2",
        800: "#584F88",
        900: "#494270",
        950: "#2E2A4B",
      },
      "red-bean": {
        50: "#FEF1F1",
        100: "#FEE6E8",
        200: "#FCCFD4",
        300: "#F9A9B2",
        400: "#F57589",
        500: "#ED4561",
        600: "#DD365B",
        700: "#B81941",
        800: "#9A183D",
        900: "#811839",
        950: "#49081B",
      },
      "green-bean": {
        50: "#F9F8EC",
        100: "#F1F0D6",
        200: "#E5E4B1",
        300: "#D2D184",
        400: "#BDBF5C",
        500: "#AFB244",
        600: "#7E822E",
        700: "#606427",
        800: "#4D5024",
        900: "#424522",
        950: "#22250E",
      },
      error: {
        25: "#FFFBFA",
        50: "#FEF3F2",
        100: "#FEE4E2",
        200: "#FECDCA",
        300: "#FDA29B",
        400: "#F97066",
        500: "#F04438",
        600: "#D92D20",
        700: "#B42318",
        800: "#912017",
        900: "#55150B",
      },
    },
    boxShadow: {
      "card-shadow": "0px 1px 6px rgba(214, 201, 181, 0.4), 0px 4px 13px rgba(232, 219, 211, 0.5)",
      "account-card": "0px 2px 4px rgba(171, 158, 138, 0.4), 0px -1px 2px rgba(241, 219, 186, 0.5)",
      "btn-shadow-gradient":
        "0px 4px 6px rgba(0, 0, 0, 0.04), 0px 4px 6px rgba(0, 0, 0, 0.04), inset 0px 3px 6px -2px rgba(255, 255, 255, 0.64), inset 0px 0px 8px -2px rgba(255, 255, 255, 0.48)",
      "btn-shadow-disabled":
        "0px -1px 3px -2px var(rgba(0,0,0,0.7)) inset, 0px 2px 3px -1px var(rgba(255,255,255,0.7)) inset, 0px 1px 1px -0.5px var(rgba(0,0,0,0.4))",
      "input-shadow": "0px 1px 3px 0px #2E25210A inset, 0px 2px 6px 0px #C7C2B666",
      none: "0 0 #0000",
    },
    borderRadius: {
      xxs: "4px",
      xs: "8px",
      sm: "10px",
      md: "12px",
      lg: "14px",
      xl: "16px",
      "2xl": "18px",
      "3xl": "20px",
      "4xl": "22px",
      "5xl": "24px",
      full: "9999px",
    },
    backgroundImage: {
      "account-card-red":
        "linear-gradient(98.89deg, #FFFBF5 5.88%, #F9E2E2 46.73%, #FFFBF4 94.73%)",
      "account-card-blue": "linear-gradient(98.89deg, #F6F6FB 18.66%, #DDDCEE 46.73%, #F6F6FB 86%)",
      "account-card-green":
        "linear-gradient(98.89deg, #F8F9EF 5.88%, #EFF0C3 46.73%, #F8F9EF 94.73%)",
      "borrow-bar-green": "linear-gradient(321.22deg, #D2D184 26.16%, #F9F8EC 111.55%)",
      "borrow-bar-red": "linear-gradient(321.25deg, #F57589 26.85%, #FFF2E2 111.56%)",
      "margin-header":
        "linear-gradient(0deg, #FFFCF6, #FFFCF6),linear-gradient(98.89deg, #F8F9EF 5.88%, #EFF0C3 46.73%, #F8F9EF 94.73%)",
    },
    fontFamily: {
      "diatype-rounded": "ABCDiatypeRounded",
      exposure: "Exposure",
    },
    fontSize: {
      xs: ["12px", { lineHeight: "140%" }],
      sm: ["14px", { lineHeight: "160%" }],
      md: ["16px", { lineHeight: "160%" }],
      lg: ["18px", { lineHeight: "140%" }],
      h4: ["20px", { lineHeight: "120%" }],
      h3: ["24px", { lineHeight: "140%" }],
      h2: ["28px", { lineHeight: "140%" }],
      h1: ["36px", { lineHeight: "140%" }],
      xl: ["40px", { lineHeight: "140%" }],
      "2xl": ["60px", { lineHeight: "140%", letterSpacing: "-2%" }],
    },
    animation: {
      "rotate-2": "rotate 4s linear infinite",
      "rotate-4": "rotate 4s linear infinite",
      "dash-4": "dash 2s ease-in-out infinite",
      "spinner-ease-spin": "spinner-spin 0.8s ease infinite",
      "spinner-linear-spin": "spinner-spin 0.8s linear infinite",
      pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
    },
    keyframes: {
      "spinner-spin": {
        "0%": {
          transform: "rotate(0deg)",
        },
        "100%": {
          transform: "rotate(360deg)",
        },
      },
      rotate: {
        "100%": {
          transform: "rotate(360deg)",
        },
      },
      dash: {
        "0%": { "stroke-dasharray": "1, 200", "stroke-dashoffset": "0" },
        "50%": { "stroke-dasharray": "90, 200", "stroke-dashoffset": "-35px" },
        "100%": { "stroke-dashoffset": "-125px" },
      },
      pulse: {
        "50%": { opacity: "0.5" },
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    tailwindScrollbar({ nocompatible: true }),
    plugin(({ addUtilities, addComponents, theme }) => {
      addUtilities({
        /* diatype */
        ".display-2xl": {
          fontWeight: "800",
          fontSize: "3.75rem",
          lineHeight: "5.25rem",
          fontFamily: theme("fontFamily.diatype-rounded"),
          letterSpacing: "-2%",
        },
        ".display-xl": {
          fontWeight: "800",
          fontSize: "2.5rem",
          lineHeight: "3.5rem",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".display-3xs": {
          fontWeight: "800",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-regular": {
          fontWeight: "400",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-medium": {
          fontWeight: "500",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-bold": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-regular": {
          fontWeight: "400",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-medium": {
          fontWeight: "500",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-bold": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-heavy": {
          fontWeight: "800",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-regular": {
          fontWeight: "400",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-medium": {
          fontWeight: "500",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-bold": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-heavy": {
          fontWeight: "800",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-regular": {
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-medium": {
          fontWeight: "500",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-bold": {
          fontWeight: "700",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-regular": {
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-medium": {
          fontWeight: "500",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-bold": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-heavy": {
          fontWeight: "800",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-regular": {
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "1",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-medium": {
          fontWeight: "500",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-bold": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-heavy": {
          fontWeight: "800",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-regular": {
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-medium": {
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-bold": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-heavy": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-xs-medium": {
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-xs-bold": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        /* Exposure */
        ".display-heading-4xs": {
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-3xs": {
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-2xs": {
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "28px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-xs": {
          fontWeight: "400",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-m": {
          fontWeight: "400",
          fontSize: "30px",
          lineHeight: "42px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-l": {
          fontWeight: "400",
          fontSize: "36px",
          lineHeight: "43.2px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-xl": {
          fontWeight: "400",
          fontSize: "40px",
          lineHeight: "48px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-2xl": {
          fontWeight: "400",
          fontSize: "60px",
          lineHeight: "72px",
          fontFamily: theme("fontFamily.exposure"),
          letterSpacing: "-2%",
        },
        ".exposure-h1-regular": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h1-italic": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h2-regular": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "59.2px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h2-italic": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "59.2px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h3-regular": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h3-italic": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-l-regular": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-l-italic": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-m-regular": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-m-italic": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-sm-regular": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "19.6px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-sm-italic": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "19.6px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-xs-regular": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-xs-italic": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
      });
      addUtilities({
        ".tap-highlight-transparent": {
          "-webkit-tap-highlight-color": "transparent",
        },
        ".drag-none": {
          "-webkit-user-drag": "none",
          "-khtml-user-drag": "none",
          "-moz-user-drag": "none",
          "-o-user-drag": "none",
          "user-drag": "none",
        },
      });
    }),
  ],
};
