import tailwindScrollbar from "tailwind-scrollbar";
import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";
export const tailwindConfig: Partial<Config> = {
  safelist: [
    {
      pattern: /grid-cols-.+/,
    },
  ],
  theme: {
    extend: {
      colors: {
        "bg-primary-rice": "var(--color-bg-primary-rice)",
        "bg-secondary-rice": "var(--color-bg-secondary-rice)",
        "bg-tertiary-rice": "var(--color-bg-tertiary-rice)",
        "button-green": "var(--color-button-green)",
        primary: {
          blue: "var(--color-primary-blue)",
          red: "var(--color-primary-red)",
          rice: "var(--color-primary-rice)",
          "900": "var(--color-primary-900)",
        },
        secondary: {
          "700": "var(--color-secondary-700)",
          blue: "var(--color-secondary-blue)",
          rice: "var(--color-secondary-rice)",
          gray: "var(--color-secondary-gray)",
        },
        tertiary: {
          rice: "var(--color-tertiary-rice)",
          "500": "var(--color-tertiary-500)",
        },
        quaternary: {
          rice: "var(--color-bg-quaternary-rice)",
        },
        transparent: "transparent",
        status: {
          success: "#25B12A",
          fail: "#E71818",
        },
        black: {
          DEFAULT: "#000000",
        },
        gray: {
          "25": "rgb(250 250 250)",
          "50": "rgb(245 244 244)",
          "100": "rgb(234 233 233)",
          "200": "rgb(214 212 211)",
          "300": "rgb(172 169 167)",
          "400": "rgb(131 125 123)",
          "500": "rgb(110 104 101)",
          "600": "rgb(89 82 79)",
          "700": "rgb(69 61 57)",
          "800": "rgb(48 39 35)",
          "900": "rgb(46 37 33)",
        },
        white: {
          DEFAULT: "#FFFFFF",
          "100": "rgb(255 252 246)",
          "200": "rgb(255 251 240)",
          "300": "rgb(255 249 229)",
          "400": "rgb(255 243 204)",
        },
        rice: {
          "950": "rgb(60 25 12)",
          "900": "rgb(105 51 30)",
          "800": "rgb(127 62 33)",
          "700": "rgb(156 77 33)",
          "600": "rgb(187 106 36)",
          "500": "rgb(212 136 44)",
          "400": "rgb(220 165 67)",
          "300": "rgb(227 189 102)",
          "200": "rgb(239 218 164)",
          "100": "rgb(243 229 191)",
          "50": "rgb(255 243 225)",
          "25": "rgb(255 249 240)",
        },
        brown: {
          "950": "rgb(48 39 35)",
          "900": "rgb(74 63 57)",
          "800": "rgb(85 71 62)",
          "700": "rgb(98 83 70)",
          "600": "rgb(122 105 84)",
          "500": "rgb(142 127 100)",
          "400": "rgb(157 143 114)",
          "300": "rgb(179 170 145)",
          "200": "rgb(207 201 185)",
          "100": "rgb(230 228 219)",
          "50": "rgb(245 244 241)",
        },
        blue: {
          "950": "rgb(46 42 75)",
          "900": "rgb(73 66 112)",
          "800": "rgb(88 79 136)",
          "700": "rgb(106 95 162)",
          "600": "rgb(123 113 182)",
          "500": "rgb(145 140 198)",
          "400": "rgb(169 168 213)",
          "300": "rgb(203 203 231)",
          "200": "rgb(226 227 242)",
          "100": "rgb(240 241 247)",
          "50": "rgb(247 248 251)",
        },
        "red-bean": {
          "950": "rgb(73 8 27)",
          "900": "rgb(129 24 57)",
          "800": "rgb(154 24 61)",
          "700": "rgb(184 25 65)",
          "600": "rgb(221 54 91)",
          "500": "rgb(237 69 97)",
          "400": "rgb(245 117 137)",
          "300": "rgb(249 169 178)",
          "200": "rgb(252 207 212)",
          "100": "rgb(254 230 232)",
          "50": "rgb(254 241 241)",
        },
        "green-bean": {
          "950": "rgb(34 37 14)",
          "900": "rgb(66 69 34)",
          "800": "rgb(77 80 36)",
          "700": "rgb(96 100 39)",
          "600": "rgb(126 130 46)",
          "500": "rgb(175 178 68)",
          "400": "rgb(189 191 92)",
          "300": "rgb(210 209 132)",
          "200": "rgb(229 228 177)",
          "100": "rgb(241 240 214)",
          "50": "rgb(249 248 236)",
        },
        error: {
          "25": "rgb(255 251 250)",
          "50": "rgb(254 243 242)",
          "100": "rgb(254 228 226)",
          "200": "rgb(254 205 202)",
          "300": "rgb(253 162 155)",
          "400": "rgb(249 112 102)",
          "500": "rgb(240 68 56)",
          "600": "rgb(217 45 32)",
          "700": "rgb(180 35 24)",
          "800": "rgb(145 32 24)",
          "900": "rgb(122 39 26)",
          "950": "rgb(85 22 12)",
        },
      },
      boxShadow: {
        "card-shadow":
          "0px 1px 6px rgba(214, 201, 181, 0.4), 0px 4px 13px rgba(232, 219, 211, 0.5)",
        "account-card": "var(--shadow-card)",
        "btn-shadow-gradient": "var(--shadow-btn-shadow-gradient)",
        "btn-shadow-disabled":
          "0px -1px 3px -2px var(rgba(0,0,0,0.7)) inset, 0px 2px 3px -1px var(rgba(255,255,255,0.7)) inset, 0px 1px 1px -0.5px var(rgba(0,0,0,0.4))",
        "input-shadow": "0px 1px 3px 0px #2E25210A inset, 0px 2px 6px 0px #C7C2B666",
        none: "0 0 #0000",
      },
      borderRadius: {
        xxs: "4px",
        xs: "8px",
        sm: "10px",
        md: "12px",
        lg: "14px",
        xl: "16px",
        "2xl": "18px",
        "3xl": "20px",
        "4xl": "22px",
        "5xl": "24px",
        full: "9999px",
      },
      backgroundImage: {
        "account-card-red": "var(--color-bg-card-red)",
        "account-card-blue":
          "linear-gradient(98.89deg, #F6F6FB 18.66%, #DDDCEE 46.73%, #F6F6FB 86%)",
        "account-card-green": "var(--color-bg-card-green)",
        "account-card-contract":
          "linear-gradient(98.89deg,#fff5e6 18.66%,#fce5c4 46.73%,#fff5e6 86%)",
        "borrow-bar-green": "linear-gradient(321.22deg, #D2D184 26.16%, #F9F8EC 111.55%)",
        "borrow-bar-red": "linear-gradient(321.25deg, #F57589 26.85%, #FFF2E2 111.56%)",
        "margin-header":
          "linear-gradient(0deg, #FFFCF6, #FFFCF6),linear-gradient(98.89deg, #F8F9EF 5.88%, #EFF0C3 46.73%, #F8F9EF 94.73%)",
        quest:
          "linear-gradient(170deg, rgba(245,117,137,1) 0%, rgba(249,169,178,1) 35%, rgba(254,241,241,1) 100%)",
      },
      fontFamily: {
        "diatype-rounded": "ABCDiatypeRounded",
        "diatype-mono": "ABCDiatypeRoundedMono",
        exposure: "Exposure",
      },
      fontSize: {
        xs: ["12px", { lineHeight: "140%" }],
        sm: ["14px", { lineHeight: "160%" }],
        md: ["16px", { lineHeight: "160%" }],
        lg: ["18px", { lineHeight: "140%" }],
        h4: ["20px", { lineHeight: "120%" }],
        h3: ["24px", { lineHeight: "140%" }],
        h2: ["28px", { lineHeight: "140%" }],
        h1: ["36px", { lineHeight: "140%" }],
        xl: ["40px", { lineHeight: "140%" }],
        "2xl": ["60px", { lineHeight: "140%", letterSpacing: "-2%" }],
      },
      animation: {
        "rotate-2": "rotate 4s linear infinite",
        "rotate-4": "rotate 4s linear infinite",
        "dash-4": "dash 2s ease-in-out infinite",
        "spinner-ease-spin": "spinner-spin 0.8s ease infinite",
        "spinner-linear-spin": "spinner-spin 0.8s linear infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        "spinner-spin": {
          "0%": {
            transform: "rotate(0deg)",
          },
          "100%": {
            transform: "rotate(360deg)",
          },
        },
        rotate: {
          "100%": {
            transform: "rotate(360deg)",
          },
        },
        dash: {
          "0%": { "stroke-dasharray": "1, 200", "stroke-dashoffset": "0" },
          "50%": { "stroke-dasharray": "90, 200", "stroke-dashoffset": "-35px" },
          "100%": { "stroke-dashoffset": "-125px" },
        },
        pulse: {
          "50%": { opacity: "0.5" },
        },
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    tailwindScrollbar({ nocompatible: true }),
    plugin(({ addUtilities, addComponents, theme }) => {
      addUtilities({
        /* diatype */
        ".display-2xl": {
          fontWeight: "800",
          fontSize: "3.75rem",
          lineHeight: "5.25rem",
          fontFamily: theme("fontFamily.diatype-rounded"),
          letterSpacing: "-2%",
        },
        ".display-xl": {
          fontWeight: "800",
          fontSize: "2.5rem",
          lineHeight: "3.5rem",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".display-3xs": {
          fontWeight: "800",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-regular": {
          fontWeight: "400",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-medium": {
          fontWeight: "500",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-bold": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-regular": {
          fontWeight: "400",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-medium": {
          fontWeight: "500",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-bold": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-heavy": {
          fontWeight: "800",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-regular": {
          fontWeight: "400",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-medium": {
          fontWeight: "500",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-bold": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-heavy": {
          fontWeight: "800",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-regular": {
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-medium": {
          fontWeight: "500",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-bold": {
          fontWeight: "700",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-heavy": {
          fontWeight: "800",
          fontSize: "20px",
          lineHeight: "140%",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-regular": {
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-medium": {
          fontWeight: "500",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-bold": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-heavy": {
          fontWeight: "800",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-regular": {
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "1",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-medium": {
          fontWeight: "500",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-bold": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-heavy": {
          fontWeight: "800",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-regular": {
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-medium": {
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-bold": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-heavy": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-xs-medium": {
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-xs-regular": {
          fontWeight: "400",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-xs-bold": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        /* Diatype Mono */
        ".diatype-mono-lg-bold": {
          fontWeight: "600",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        ".diatype-mono-m-bold": {
          fontWeight: "600",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        ".diatype-mono-sm-bold": {
          fontWeight: "600",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        ".diatype-mono-sm-medium": {
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        ".diatype-mono-xs-medium": {
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        /* Exposure */
        ".display-heading-4xs": {
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-3xs": {
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-2xs": {
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "28px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-xs": {
          fontWeight: "400",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-m": {
          fontWeight: "400",
          fontSize: "30px",
          lineHeight: "42px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-l": {
          fontWeight: "400",
          fontSize: "36px",
          lineHeight: "43.2px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-xl": {
          fontWeight: "400",
          fontSize: "40px",
          lineHeight: "48px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-2xl": {
          fontWeight: "400",
          fontSize: "60px",
          lineHeight: "72px",
          fontFamily: theme("fontFamily.exposure"),
          letterSpacing: "-2%",
        },
        ".exposure-h1-regular": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h1-italic": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h2-regular": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "59.2px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h2-italic": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "59.2px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h3-regular": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h3-italic": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-l-regular": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-l-italic": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-m-regular": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-m-italic": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-sm-regular": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "19.6px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-sm-italic": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "19.6px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-xs-regular": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-xs-italic": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
      });
      addUtilities({
        ".tap-highlight-transparent": {
          "-webkit-tap-highlight-color": "transparent",
        },
        ".drag-none": {
          "-webkit-user-drag": "none",
          "-khtml-user-drag": "none",
          "-moz-user-drag": "none",
          "-o-user-drag": "none",
          "user-drag": "none",
        },
      });
    }),
  ],
};
