//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    blocks::Entity as Blocks, events::Entity as Events, messages::Entity as Messages,
    transactions::Entity as Transactions,
};
