- name: Load debian root secrets
  community.sops.load_vars:
    file: vaults/debian/root_vault.sops.json
  no_log: true
  become: false

- name: Gather facts after loading debian root secrets
  ansible.builtin.setup:
