- name: Load debian root secrets
  community.sops.load_vars:
    file: vaults/debian/root_vault.sops.json
    return_method: facts-only
  when: not (debian_root_secrets_loaded | default(false))
  register: debian_root_secrets_load
  no_log: true
  become: false

- name: Mark debian root secrets as loaded
  ansible.builtin.set_fact:
    debian_root_secrets_loaded: true
  when: debian_root_secrets_load is not skipped
  no_log: true
  become: false

- name: Gather facts after loading debian root secrets
  ansible.builtin.setup:
