import tailwindScrollbar from "tailwind-scrollbar";
import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";
export const tailwindConfig: Partial<Config> = {
  darkMode: "class",
  safelist: [
    {
      pattern: /grid-cols-.+/,
    },
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          black: "#302723",
          green: "#AFB244",
          "red-bean": "#DD375B",
          white: "#F2E2B8",
        },
        primitives: {
          blue: {
            dark: {
              50: "#EDEEF1",
              100: "#D5D5D8",
              200: "#C8C9D5",
              300: "#9291B4",
              400: "#8685A4",
              500: "#7B7A94",
              600: "#706E83",
              700: "#646273",
              800: "#595763",
              900: "#53515B",
              950: "#47454A",
            },
            light: {
              50: "#F7F8FB",
              100: "#F0F1F7",
              200: "#E2E3F2",
              300: "#CBCBE7",
              400: "#A9A8D5",
              500: "#918CC6",
              600: "#7B71B6",
              700: "#6A5FA2",
              800: "#584F88",
              900: "#494270",
              950: "#2E2A4B",
            },
          },
          brown: {
            light: {
              50: "#F5F4F1",
              100: "#E6E4DB",
              200: "#CFC9B9",
              300: "#B3AA91",
              400: "#9D8F72",
              500: "#8E7F64",
              600: "#7A6954",
              700: "#625346",
              800: "#55473E",
              900: "#4A3F39",
              950: "#302723",
            },
          },
          gray: {
            dark: {
              25: "#FFF9F0",
              50: "#E5E0D8",
              100: "#D9D4CC",
              200: "#BFBBB4",
              300: "#999590",
              400: "#807D78",
              500: "#73706C",
              600: "#666460",
              700: "#595754",
              800: "#4D4B48",
              900: "#363432",
              950: "#2D2C2A",
            },
            light: {
              25: "#FAFAFA",
              50: "#F5F4F4",
              100: "#EAE9E9",
              200: "#D6D4D3",
              300: "#ACA9A7",
              400: "#837D7B",
              500: "#6E6865",
              600: "#59524F",
              700: "#453D39",
              800: "#302723",
              900: "#2E2521",
            },
          },
          green: {
            dark: {
              50: "#DCDBAB",
              100: "#D3D2A4",
              200: "#C2C198",
              300: "#B0AF8B",
              400: "#9F9E7E",
              500: "#8D8C72",
              600: "#7C7A65",
              700: "#6B6958",
              800: "#59574B",
              900: "#504E45",
              950: "#48463F",
            },
            light: {
              50: "#F9F8EC",
              100: "#F1F0D6",
              200: "#E5E4B1",
              300: "#D2D184",
              400: "#BDBF5C",
              500: "#AFB244",
              600: "#7E822E",
              700: "#606427",
              800: "#4D5024",
              900: "#424522",
              950: "#FFFFFF",
            },
          },
          red: {
            dark: {
              50: "#FEF1F1",
              100: "#E9D3D5",
              200: "#D3AEB2",
              300: "#BE9EA1",
              400: "#A98E90",
              500: "#947E7F",
              600: "#806D6E",
              700: "#6B5D5D",
              800: "#564D4C",
              900: "#4C4444",
              950: "#423C3B",
            },
            light: {
              50: "#FEF1F1",
              100: "#FEE6E8",
              200: "#FCCFD4",
              300: "#F9A9B2",
              400: "#F57589",
              500: "#ED4561",
              600: "#DD365B",
              700: "#881941",
              800: "#9A183D",
              900: "#811839",
              950: "#49081B",
            },
          },
          rice: {
            dark: {
              25: "#F5EFE7",
              50: "#EBE0D0",
              100: "#E1D7C7",
              200: "#CDC2A3",
              300: "#BAB095",
              400: "#A59876",
              500: "#92876B",
              600: "#807660",
              700: "#6A5D42",
              800: "#594F3C",
              900: "#474237",
              950: "#3F3B35",
            },
            light: {
              25: "#FFF9F0",
              50: "#FFF3E1",
              100: "#F3E5BF",
              200: "#EFDAA4",
              300: "#E3BD66",
              400: "#DCA543",
              500: "#D4882C",
              600: "#BB6A24",
              700: "#9C4D21",
              800: "#7F3E21",
              900: "#69331E",
              950: "#3C190C",
            },
          },
          white: {
            light: {
              100: "#FFFCF6",
              200: "#FFFBF0",
              300: "#FFF9E5",
              400: "#FFF3CC",
            },
          },
        },
        surface: {
          primary: {
            gray: "var(--color-surface-primary-gray)",
            blue: "var(--color-surface-primary-blue)",
            green: "var(--color-surface-primary-green)",
            red: "var(--color-surface-primary-red)",
            rice: "var(--color-surface-primary-rice)",
          },
          secondary: {
            blue: "var(--color-surface-secondary-blue)",
            green: "var(--color-surface-secondary-green)",
            red: "var(--color-surface-secondary-red)",
            rice: "var(--color-surface-secondary-rice)",
          },
          tertiary: {
            gray: "var(--color-surface-tertiary-gray)",
            green: "var(--color-surface-tertiary-green)",
            rice: "var(--color-surface-tertiary-rice)",
          },
          quaternary: {
            gray: "var(--color-surface-quaternary-gray)",
            green: "var(--color-surface-quaternary-green)",
            rice: "var(--color-surface-quaternary-rice)",
            "rice-hover": "var(--color-surface-quaternary-rice-hover)",
          },
          disabled: {
            gray: "var(--color-surface-disabled-gray)",
          },
          section: {
            green: "var(--color-surface-section-green)",
            red: "var(--color-surface-section-red)",
          },
          button: {
            green: "var(--color-surface-button-green)",
            "green-hover": "var(--color-surface-button-green-hover)",
          },
          playground: "var(--color-surface-playground)",
        },
        overlay: {
          primary: {
            gray: "var(--color-overlay-primary-gray)",
            blue: "var(--color-overlay-primary-blue)",
            green: "var(--color-overlay-primary-green)",
            red: "var(--color-overlay-primary-red)",
            rice: "var(--color-overlay-primary-rice)",
          },
          secondary: {
            gray: "var(--color-overlay-secondary-gray)",
            green: "var(--color-overlay-secondary-green)",
            red: "var(--color-overlay-secondary-red)",
            rice: "var(--color-overlay-secondary-rice)",
          },
          tertiary: {
            blue: "var(--color-overlay-tertiary-blue)",
            rice: "var(--color-overlay-tertiary-rice)",
          },
        },
        fg: {
          primary: {
            700: "var(--color-fg-primary-700)",
            blue: "var(--color-fg-primary-blue)",
            green: "var(--color-fg-primary-green)",
            red: "var(--color-fg-primary-red)",
            rice: "var(--color-fg-primary-rice)",
          },
          secondary: {
            500: "var(--color-fg-secondary-500)",
            blue: "var(--color-fg-secondary-blue)",
            green: "var(--color-fg-secondary-green)",
            red: "var(--color-fg-secondary-red)",
            rice: "var(--color-fg-secondary-rice)",
          },
          tertiary: {
            400: "var(--color-fg-tertiary-400)",
            blue: "var(--color-fg-tertiary-blue)",
            rice: "var(--color-fg-tertiary-rice)",
          },
          quaternary: {
            rice: "var(--color-fg-quaternary-rice)",
          },
          logo: "var(--color-fg-logo)",
          disabled: "var(--color-fg-disabled)",
        },
        ink: {
          primary: {
            900: "var(--color-ink-primary-900)",
            blue: "var(--color-ink-primary-blue)",
            green: "var(--color-ink-primary-green)",
            red: "var(--color-ink-primary-red)",
            rice: "var(--color-ink-primary-rice)",
          },
          secondary: {
            700: "var(--color-ink-secondary-700)",
            blue: "var(--color-ink-secondary-blue)",
            green: "var(--color-ink-secondary-green)",
            red: "var(--color-ink-secondary-red)",
            rice: "var(--color-ink-secondary-rice)",
          },
          tertiary: {
            500: "var(--color-ink-tertiary-500)",
            green: "var(--color-ink-tertiary-green)",
            red: "var(--color-ink-tertiary-red)",
          },
          quaternary: {
            200: "var(--color-ink-quaternary-200)",
          },
          placeholder: {
            400: "var(--color-ink-placeholder-400)",
          },
          disabled: {
            300: "var(--color-ink-disabled-300)",
            blue: "var(--color-ink-disabled-blue)",
          },
        },
        status: {
          success: "var(--color-status-success)",
          fail: "var(--color-status-fail)",
        },
        transparent: "transparent",
        /*  foreground: {
          "primary-blue": "var(--color-foreground-primary-blue)",
          "primary-red": "var(--color-foreground-primary-red)",
          "primary-green": "var(--color-foreground-primary-green)",
          "disabled-gray": "var(--color-foreground-disabled-gray)",
          "secondary-rice": "var(--color-foreground-secondary-rice)",
          tertiary: "var(--color-foreground-tertiary)",
          "tertiary-rice": "var(--color-foreground-tertiary-rice)",
          "quaternary-rice": "var(--color-foreground-quaternary-rice)",
        }, */
        /*  overlay-rice */
        /* border: {
          "secondary-rice": "var(--color-border-secondary-rice)",
          "tertiary-blue": "var(--color-border-tertiary-blue)",
        }, */
        /* "button-green": "var(--color-button-green)",
        primary: {
          blue: "var(--color-primary-blue)",
          red: "var(--color-primary-red)",
          rice: "var(--color-primary-rice)",
          "900": "var(--color-primary-900)",
          gray: "var(--color-primary-gray)",
          green: "var(--color-primary-green)",
        },
        secondary: {
          "700": "var(--color-secondary-700)",
          blue: "var(--color-secondary-blue)",
          rice: "var(--color-secondary-rice)",
          gray: "var(--color-secondary-gray)",
          red: "var(--color-secondary-red)",
          green: "var(--color-secondary-green)",
        },
        tertiary: {
          rice: "var(--color-tertiary-rice)",
          "500": "var(--color-tertiary-500)",
          green: "var(--color-tertiary-green)",
          blue: "var(--color-tertiary-blue)",
          red: "var(--color-tertiary-red)",
        },
        quaternary: {
          rice: "var(--color-surface-quaternary-rice)",
        }, */
      },
      boxShadow: {
        "account-card": "var(--shadow-card)",
        "btn-shadow-gradient": "var(--shadow-btn-shadow-gradient)",
        "btn-secondary-shadow-gradient": "var(--shadow-btn-secondary-shadow-gradient)",
        "btn-shadow-disabled":
          "0px -1px 3px -2px var(rgba(0,0,0,0.7)) inset, 0px 2px 3px -1px var(rgba(255,255,255,0.7)) inset, 0px 1px 1px -0.5px var(rgba(0,0,0,0.4))",
        "input-shadow": "0px 1px 3px 0px #2E25210A inset, 0px 2px 6px 0px #C7C2B666",
        none: "0 0 #0000",
      },
      borderRadius: {
        xxs: "4px",
        xs: "8px",
        sm: "10px",
        md: "12px",
        lg: "14px",
        xl: "16px",
        "2xl": "18px",
        "3xl": "20px",
        "4xl": "22px",
        "5xl": "24px",
        full: "9999px",
      },
      backgroundImage: {
        "account-card-red": "var(--color-bg-card-red)",
        "account-card-red-2": "var(--color-bg-card-red-2)",
        "account-card-blue": "var(--color-bg-card-blue)",
        "account-card-green": "var(--color-bg-card-green)",
        "account-card-green-2": "var(--color-bg-card-green-2)",
        "account-card-contract": "var(--color-bg-card-rice)",
        "borrow-bar-green": "linear-gradient(321.22deg, #D2D184 26.16%, #F9F8EC 111.55%)",
        "borrow-bar-red": "linear-gradient(321.25deg, #F57589 26.85%, #FFF2E2 111.56%)",
        "margin-header":
          "linear-gradient(0deg, #FFFCF6, #FFFCF6),linear-gradient(98.89deg, #F8F9EF 5.88%, #EFF0C3 46.73%, #F8F9EF 94.73%)",
        quest:
          "linear-gradient(170deg, rgba(245,117,137,1) 0%, rgba(249,169,178,1) 35%, rgba(254,241,241,1) 100%)",
      },
      fontFamily: {
        "diatype-rounded": "ABCDiatypeRounded",
        "diatype-mono": "ABCDiatypeRoundedMono",
        exposure: "Exposure",
      },
      fontSize: {
        xs: ["12px", { lineHeight: "140%" }],
        sm: ["14px", { lineHeight: "160%" }],
        md: ["16px", { lineHeight: "160%" }],
        lg: ["18px", { lineHeight: "140%" }],
        h4: ["20px", { lineHeight: "120%" }],
        h3: ["24px", { lineHeight: "140%" }],
        h2: ["28px", { lineHeight: "140%" }],
        h1: ["36px", { lineHeight: "140%" }],
        xl: ["40px", { lineHeight: "140%" }],
        "2xl": ["60px", { lineHeight: "140%", letterSpacing: "-2%" }],
      },
      animation: {
        "rotate-2": "rotate 4s linear infinite",
        "rotate-4": "rotate 4s linear infinite",
        "dash-4": "dash 2s ease-in-out infinite",
        "spinner-ease-spin": "spinner-spin 0.8s ease infinite",
        "spinner-linear-spin": "spinner-spin 0.8s linear infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        levitate: "levitate 2s ease-in-out infinite",
      },
      keyframes: {
        "spinner-spin": {
          "0%": {
            transform: "rotate(0deg)",
          },
          "100%": {
            transform: "rotate(360deg)",
          },
        },
        rotate: {
          "100%": {
            transform: "rotate(360deg)",
          },
        },
        dash: {
          "0%": { "stroke-dasharray": "1, 200", "stroke-dashoffset": "0" },
          "50%": { "stroke-dasharray": "90, 200", "stroke-dashoffset": "-35px" },
          "100%": { "stroke-dashoffset": "-125px" },
        },
        pulse: {
          "50%": { opacity: "0.5" },
        },
        levitate: {
          "0%": {
            opacity: "1",
            transform: "translateY(0px)",
          },
          "50%": {
            opacity: "0.4",
            transform: "translateY(-10px)",
          },
          "100%": {
            opacity: "1",
            transform: "translateY(0px)",
          },
        },
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    tailwindScrollbar({ nocompatible: true }),
    plugin(({ addUtilities, addComponents, theme }) => {
      addUtilities({
        /* diatype */
        ".display-2xl": {
          fontWeight: "800",
          fontSize: "3.75rem",
          lineHeight: "5.25rem",
          fontFamily: theme("fontFamily.diatype-rounded"),
          letterSpacing: "-2%",
        },
        ".display-xl": {
          fontWeight: "800",
          fontSize: "2.5rem",
          lineHeight: "3.5rem",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".display-3xs": {
          fontWeight: "800",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-regular": {
          fontWeight: "400",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-medium": {
          fontWeight: "500",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h1-bold": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-regular": {
          fontWeight: "400",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-medium": {
          fontWeight: "500",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-bold": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h2-heavy": {
          fontWeight: "800",
          fontSize: "28px",
          lineHeight: "39.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-regular": {
          fontWeight: "400",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-medium": {
          fontWeight: "500",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-bold": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h3-heavy": {
          fontWeight: "800",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-regular": {
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-medium": {
          fontWeight: "500",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-bold": {
          fontWeight: "700",
          fontSize: "20px",
          lineHeight: "24px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".h4-heavy": {
          fontWeight: "800",
          fontSize: "20px",
          lineHeight: "140%",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-regular": {
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-medium": {
          fontWeight: "500",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-bold": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-lg-heavy": {
          fontWeight: "800",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-regular": {
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "1",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-medium": {
          fontWeight: "500",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-bold": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-m-heavy": {
          fontWeight: "800",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-regular": {
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-medium": {
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-bold": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-sm-heavy": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-xs-medium": {
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-xs-regular": {
          fontWeight: "400",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        ".diatype-xs-bold": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-rounded"),
        },
        /* Diatype Mono */
        ".diatype-mono-lg-bold": {
          fontWeight: "600",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        ".diatype-mono-m-bold": {
          fontWeight: "600",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        ".diatype-mono-sm-bold": {
          fontWeight: "600",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        ".diatype-mono-sm-medium": {
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "22.4px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        ".diatype-mono-xs-medium": {
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontFamily: theme("fontFamily.diatype-mono"),
        },
        /* Exposure */
        ".display-heading-4xs": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-3xs": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-2xs": {
          fontWeight: "700",
          fontSize: "20px",
          lineHeight: "28px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-xs": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-m": {
          fontWeight: "700",
          fontSize: "30px",
          lineHeight: "42px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-l": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "43.2px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-xl": {
          fontWeight: "700",
          fontSize: "40px",
          lineHeight: "48px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".display-heading-2xl": {
          fontWeight: "700",
          fontSize: "60px",
          lineHeight: "72px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
          letterSpacing: "-2%",
        },
        ".exposure-h1-italic": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "50.4px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h2-italic": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "59.2px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-h3-italic": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "33.6px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-l-italic": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "25.2px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-m-italic": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "22.4px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-sm-italic": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "19.6px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
        ".exposure-xs-italic": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "16.8px",
          fontStyle: "italic",
          fontFamily: theme("fontFamily.exposure"),
        },
      });
      addUtilities({
        ".tap-highlight-transparent": {
          "-webkit-tap-highlight-color": "transparent",
        },
        ".drag-none": {
          "-webkit-user-drag": "none",
          "-khtml-user-drag": "none",
          "-moz-user-drag": "none",
          "-o-user-drag": "none",
          "user-drag": "none",
        },
      });
    }),
  ],
};
