export const CHARACTERS = [
  "frog1",
  "clouds",
  "frog2",
  "dog1",
  "bird2",
  "rich-cocodrile",
  "hippo",
  "pig",
  "candle",
  "bird-lost",
  "bird-militar",
  "cocodrile_winner",
  "dango-king",
  "dango_winner",
  "pirate",
  "smoke-cocodrile",
] as const;
