use {
    crate::{context::Context, entities::perps_fees::PerpsFeesAndRevenue},
    async_graphql::*,
    chrono::{DateTime, Utc},
};

#[derive(Default, Debug)]
pub struct PerpsFeesQuery;

#[Object]
impl PerpsFeesQuery {
    /// Sum of fees and revenue generated by the perps contract within the
    /// inclusive `[from, to]` time window. Values come from pre-aggregated
    /// per-block rows built from `FeeDistributed` events.
    async fn perps_fees_and_revenue(
        &self,
        ctx: &async_graphql::Context<'_>,
        #[graphql(desc = "Window lower bound (inclusive)")] from: DateTime<Utc>,
        #[graphql(desc = "Window upper bound (inclusive)")] to: DateTime<Utc>,
    ) -> Result<PerpsFeesAndRevenue> {
        if from > to {
            return Err(Error::new("`from` must be less than or equal to `to`"));
        }

        let app_ctx = ctx.data::<Context>()?;
        let clickhouse_client = app_ctx.clickhouse_client();

        PerpsFeesAndRevenue::fetch(clickhouse_client, from, to)
            .await
            .map_err(|e| Error::new(e.to_string()))
    }
}
