export const coins = {
  dango: {
    type: "native",
    name: "Dango",
    logoURI: "/DGX.svg",
    symbol: "DGX",
    denom: "dango",
    decimals: 6,
  },
  "bridge/btc": {
    type: "native",
    name: "Bitcoin",
    logoURI: "/images/coins/bitcoin.svg",
    symbol: "BTC",
    denom: "bridge/btc",
    decimals: 8,
  },
  "bridge/eth": {
    type: "native",
    name: "Ether",
    logoURI: "/images/coins/eth.svg",
    symbol: "ETH",
    denom: "bridge/eth",
    decimals: 18,
  },
  "bridge/xrp": {
    type: "native",
    name: "XRP",
    logoURI: "/images/coins/xrp.svg",
    symbol: "XRP",
    denom: "bridge/xrp",
    decimals: 6,
  },
  "bridge/usdc": {
    type: "native",
    name: "USD Coin",
    logoURI: "/images/coins/usdc.svg",
    symbol: "USDC",
    denom: "bridge/usdc",
    decimals: 6,
  },
  "bridge/sol": {
    type: "native",
    name: "Solana",
    logoURI: "/images/coins/sol.svg",
    symbol: "SOL",
    denom: "bridge/sol",
    decimals: 9,
  },
  "bridge/hype": {
    type: "native",
    name: "Hype",
    logoURI: "/images/coins/hype.svg",
    symbol: "HYPE",
    denom: "bridge/hype",
    decimals: 18,
  },
  "perp/xauusd": {
    type: "native",
    name: "Gold",
    logoURI: "/images/coins/gold.svg",
    symbol: "XAU",
    denom: "perp/xauusd",
    decimals: 0,
  },
  "perp/xagusd": {
    type: "native",
    name: "Silver",
    logoURI: "/images/coins/silver.svg",
    symbol: "XAG",
    denom: "perp/xagusd",
    decimals: 0,
  },
  "perp/wtiusd": {
    type: "native",
    name: "WTI Oil",
    logoURI: "/images/coins/wtioil.svg",
    symbol: "WTI",
    denom: "perp/wtiusd",
    decimals: 0,
  },
  "perp/brentusd": {
    type: "native",
    name: "Brent Oil",
    logoURI: "/images/coins/brentoil.svg",
    symbol: "BRENT",
    denom: "perp/brentusd",
    decimals: 0,
  },
} as const;
