export const coins = {
  dango: {
    type: "native",
    name: "Dango",
    logoURI: "/DGX.svg",
    symbol: "DGX",
    denom: "dango",
    decimals: 6,
  },
  "bridge/btc": {
    type: "native",
    name: "Bitcoin",
    logoURI: "/images/coins/bitcoin.svg",
    symbol: "BTC",
    denom: "bridge/btc",
    decimals: 8,
    coingeckoId: "bitcoin",
  },
  "bridge/eth": {
    type: "native",
    name: "Ether",
    logoURI: "/images/coins/eth.svg",
    symbol: "ETH",
    denom: "bridge/eth",
    decimals: 18,
    coingeckoId: "ethereum",
  },
  "bridge/xrp": {
    type: "native",
    name: "XRP",
    logoURI: "/images/coins/xrp.svg",
    symbol: "XRP",
    denom: "bridge/xrp",
    decimals: 6,
    coingeckoId: "ripple",
  },
  "bridge/usdc": {
    type: "native",
    name: "USD Coin",
    logoURI: "/images/coins/usdc.svg",
    symbol: "USDC",
    denom: "bridge/usdc",
    decimals: 6,
    coingeckoId: "usd-coin",
  },
  "bridge/sol": {
    type: "native",
    name: "Solana",
    logoURI: "/images/coins/sol.svg",
    symbol: "SOL",
    denom: "bridge/sol",
    decimals: 9,
    coingeckoId: "solana",
  },
  "bridge/hype": {
    type: "native",
    name: "Hype",
    logoURI: "/images/coins/hype.svg",
    symbol: "HYPE",
    denom: "bridge/hype",
    decimals: 18,
  },
  "bridge/gold": {
    type: "native",
    name: "Gold",
    logoURI: "/images/coins/gold.svg",
    symbol: "GOLD",
    denom: "bridge/gold",
    decimals: 0,
  },
  "bridge/silver": {
    type: "native",
    name: "Silver",
    logoURI: "/images/coins/silver.svg",
    symbol: "SILVER",
    denom: "bridge/silver",
    decimals: 0,
  },
  "bridge/wtioil": {
    type: "native",
    name: "WTI Oil",
    logoURI: "/images/coins/wtioil.svg",
    symbol: "WTIOIL",
    denom: "bridge/wtioil",
    decimals: 0,
  },
  "bridge/brentoil": {
    type: "native",
    name: "Brent Oil",
    logoURI: "/images/coins/brentoil.svg",
    symbol: "BRENTOIL",
    denom: "bridge/brentoil",
    decimals: 0,
  },
} as const;
