api:
  dashboard: true
  insecure: true

ping: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /config
    watch: true

serversTransport:
  maxIdleConnsPerHost: 4096
  forwardingTimeouts:
    dialTimeout: 10s
    responseHeaderTimeout: 60s

entryPoints:
  # Public (all interfaces)
  web:
    address: :80
    reusePort: true
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 0s
      respondingTimeouts:
        readTimeout: 60s
    forwardedHeaders:
      trustedIPs:
{% for cidr in cloudflare_ips %}
        - {{ cidr }}
{% endfor %}
        - 127.0.0.1/32
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - fc00::/7
  websecure:
    address: :443
    reusePort: true
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 0s
      respondingTimeouts:
        readTimeout: 60s
    forwardedHeaders:
      trustedIPs:
{% for cidr in cloudflare_ips %}
        - {{ cidr }}
{% endfor %}
        - 127.0.0.1/32
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - fc00::/7
  traefik:
    address: :8888

metrics:
  prometheus: {}

log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    names:
      RouterName: keep
      ServiceName: keep
    headers:
      defaultMode: drop
      names:
        CF-Connecting-IP: keep
        X-Forwarded-For: keep
        Forwarded: keep
        True-Client-IP: keep
        X-Real-IP: keep
        Cf-Ray: keep
