import { defineConfig } from "vocs";

// TODO(docs): once drafters start adding TS code samples with type-checked
// snippets, decide whether to wire `@shikijs/twoslash` here via the `markdown`
// option. If we adopt it, set `defaultCompilerOptions: { allowJs: true }` (and
// likely `noErrorTruncation: true`) so partial-type snippets don't fail the
// build. For now we use Vocs' default Shiki highlighting and no twoslash.
export default defineConfig({
  title: "Dango SDK",
  description: "Reference and concept docs for the TypeScript, Python, and Rust Dango SDKs.",
  rootDir: ".",
  logoUrl: "/dango-logo.svg",
  iconUrl: "/favicon.svg",
  sidebar: {
    "/typescript/": typescriptSidebar(),
    "/python/": pythonSidebar(),
    "/rust/": rustSidebar(),
  },
  topNav: [
    { text: "TypeScript", link: "/typescript/" },
    { text: "Python", link: "/python/" },
    { text: "Rust", link: "/rust/" },
  ],
  socials: [
    { icon: "github", link: "https://github.com/left-curve/left-curve" },
    { icon: "discord", link: "https://discord.gg/BWJtyySxBM" },
    { icon: "x", link: "https://x.com/dango" },
  ],
});

// Sidebars below follow `sdk/docs/.templates/sitemap.md`.
// Hrefs are placeholders: pages don't exist yet and will be added by drafters.

function typescriptSidebar() {
  return [
    {
      text: "Getting Started",
      items: [
        { text: "Installation", link: "/typescript/getting-started/installation" },
        { text: "First Call", link: "/typescript/getting-started/first-call" },
        { text: "Project Setup", link: "/typescript/getting-started/project-setup" },
      ],
    },
    {
      text: "Concepts",
      collapsed: true,
      items: [
        { text: "Packages", link: "/typescript/concepts/packages" },
        { text: "Clients", link: "/typescript/concepts/clients" },
        { text: "Signers & Authentication", link: "/typescript/concepts/signers-and-authentication" },
        { text: "Transactions", link: "/typescript/concepts/transactions" },
        { text: "Subscriptions", link: "/typescript/concepts/subscriptions" },
        { text: "Encoding & Types", link: "/typescript/concepts/encoding-and-types" },
        { text: "Error Handling", link: "/typescript/concepts/error-handling" },
        { text: "Rate Limits & Quotas", link: "/typescript/concepts/rate-limits" },
      ],
    },
    {
      text: "API Reference",
      items: [
        {
          text: "Clients",
          collapsed: true,
          items: [
            { text: "createPublicClient", link: "/typescript/clients/createPublicClient" },
            { text: "createSignerClient", link: "/typescript/clients/createSignerClient" },
            { text: "createBaseClient", link: "/typescript/clients/createBaseClient" },
          ],
        },
    {
      text: "Actions: App",
      collapsed: true,
      items: [
        { text: "getAppConfig", link: "/typescript/actions/app/getAppConfig" },
        { text: "getBalance", link: "/typescript/actions/app/getBalance" },
        { text: "getBalances", link: "/typescript/actions/app/getBalances" },
        { text: "getSupply", link: "/typescript/actions/app/getSupply" },
        { text: "getSupplies", link: "/typescript/actions/app/getSupplies" },
        { text: "getCode", link: "/typescript/actions/app/getCode" },
        { text: "getCodes", link: "/typescript/actions/app/getCodes" },
        { text: "getContractInfo", link: "/typescript/actions/app/getContractInfo" },
        { text: "getContractsInfo", link: "/typescript/actions/app/getContractsInfo" },
        { text: "queryWasmRaw", link: "/typescript/actions/app/queryWasmRaw" },
        { text: "queryWasmSmart", link: "/typescript/actions/app/queryWasmSmart" },
        { text: "queryApp", link: "/typescript/actions/app/queryApp" },
        { text: "queryStatus", link: "/typescript/actions/app/queryStatus" },
        { text: "queryTx", link: "/typescript/actions/app/queryTx" },
        { text: "simulate", link: "/typescript/actions/app/simulate" },
        { text: "broadcastTxSync", link: "/typescript/actions/app/broadcastTxSync" },
        { text: "signAndBroadcastTx", link: "/typescript/actions/app/signAndBroadcastTx" },
        { text: "transfer", link: "/typescript/actions/app/transfer" },
        { text: "execute", link: "/typescript/actions/app/execute" },
        { text: "instantiate", link: "/typescript/actions/app/instantiate" },
        { text: "migrate", link: "/typescript/actions/app/migrate" },
        { text: "storeCode", link: "/typescript/actions/app/storeCode" },
        { text: "storeCodeAndInstantiate", link: "/typescript/actions/app/storeCodeAndInstantiate" },
        { text: "upgrade", link: "/typescript/actions/app/upgrade" },
        { text: "configure", link: "/typescript/actions/app/configure" },
      ],
    },
    {
      text: "Actions: Account Factory",
      collapsed: true,
      items: [
        { text: "forgotUsername", link: "/typescript/actions/account-factory/forgotUsername" },
        { text: "getAccountInfo", link: "/typescript/actions/account-factory/getAccountInfo" },
        { text: "getAccountSeenNonces", link: "/typescript/actions/account-factory/getAccountSeenNonces" },
        { text: "getAccountStatus", link: "/typescript/actions/account-factory/getAccountStatus" },
        { text: "getAllAccountInfo", link: "/typescript/actions/account-factory/getAllAccountInfo" },
        { text: "getCodeHash", link: "/typescript/actions/account-factory/getCodeHash" },
        { text: "getNextAccountIndex", link: "/typescript/actions/account-factory/getNextAccountIndex" },
        { text: "getUser", link: "/typescript/actions/account-factory/getUser" },
        { text: "getUserKeys", link: "/typescript/actions/account-factory/getUserKeys" },
        { text: "registerUser", link: "/typescript/actions/account-factory/registerUser" },
        { text: "registerAccount", link: "/typescript/actions/account-factory/registerAccount" },
        { text: "updateKey", link: "/typescript/actions/account-factory/updateKey" },
        { text: "updateUsername", link: "/typescript/actions/account-factory/updateUsername" },
        { text: "createSession", link: "/typescript/actions/account-factory/createSession" },
      ],
    },
    {
      text: "Actions: DEX",
      collapsed: true,
      items: [
        { text: "dexStatus", link: "/typescript/actions/dex/dexStatus" },
        { text: "getOrder", link: "/typescript/actions/dex/getOrder" },
        { text: "getPair", link: "/typescript/actions/dex/getPair" },
        { text: "getPairs", link: "/typescript/actions/dex/getPairs" },
        { text: "getPairStats", link: "/typescript/actions/dex/getPairStats" },
        { text: "getAllPairStats", link: "/typescript/actions/dex/getAllPairStats" },
        { text: "ordersByUser", link: "/typescript/actions/dex/ordersByUser" },
        { text: "queryCandles", link: "/typescript/actions/dex/queryCandles" },
        { text: "queryTrades", link: "/typescript/actions/dex/queryTrades" },
        { text: "simulateSwapExactAmountIn", link: "/typescript/actions/dex/simulateSwapExactAmountIn" },
        { text: "simulateSwapExactAmountOut", link: "/typescript/actions/dex/simulateSwapExactAmountOut" },
        { text: "simulateWithdrawLiquidity", link: "/typescript/actions/dex/simulateWithdrawLiquidity" },
        { text: "batchUpdateOrders", link: "/typescript/actions/dex/batchUpdateOrders" },
        { text: "swapExactAmountIn", link: "/typescript/actions/dex/swapExactAmountIn" },
        { text: "swapExactAmountOut", link: "/typescript/actions/dex/swapExactAmountOut" },
        { text: "provideLiquidity", link: "/typescript/actions/dex/provideLiquidity" },
        { text: "withdrawLiquidity", link: "/typescript/actions/dex/withdrawLiquidity" },
      ],
    },
    {
      text: "Actions: Perps",
      collapsed: true,
      items: [
        { text: "getPerpsUserState", link: "/typescript/actions/perps/getPerpsUserState" },
        { text: "getPerpsUserStateExtended", link: "/typescript/actions/perps/getPerpsUserStateExtended" },
        { text: "getPerpsOrdersByUser", link: "/typescript/actions/perps/getPerpsOrdersByUser" },
        { text: "getPerpsLiquidityDepth", link: "/typescript/actions/perps/getPerpsLiquidityDepth" },
        { text: "getPerpsPairParam", link: "/typescript/actions/perps/getPerpsPairParam" },
        { text: "getPerpsPairParams", link: "/typescript/actions/perps/getPerpsPairParams" },
        { text: "getPerpsParam", link: "/typescript/actions/perps/getPerpsParam" },
        { text: "getPerpsPairStats", link: "/typescript/actions/perps/getPerpsPairStats" },
        { text: "getAllPerpsPairStats", link: "/typescript/actions/perps/getAllPerpsPairStats" },
        { text: "getPerpsPairState", link: "/typescript/actions/perps/getPerpsPairState" },
        { text: "getPerpsState", link: "/typescript/actions/perps/getPerpsState" },
        { text: "getPerpsVaultState", link: "/typescript/actions/perps/getPerpsVaultState" },
        { text: "getVaultSnapshots", link: "/typescript/actions/perps/getVaultSnapshots" },
        { text: "getFeeRateOverride", link: "/typescript/actions/perps/getFeeRateOverride" },
        { text: "queryPerpsCandles", link: "/typescript/actions/perps/queryPerpsCandles" },
        { text: "queryPerpsEvents", link: "/typescript/actions/perps/queryPerpsEvents" },
        { text: "depositMargin", link: "/typescript/actions/perps/depositMargin" },
        { text: "withdrawMargin", link: "/typescript/actions/perps/withdrawMargin" },
        { text: "submitPerpsOrder", link: "/typescript/actions/perps/submitPerpsOrder" },
        { text: "cancelPerpsOrder", link: "/typescript/actions/perps/cancelPerpsOrder" },
        { text: "submitConditionalOrder", link: "/typescript/actions/perps/submitConditionalOrder" },
        { text: "submitConditionalOrders", link: "/typescript/actions/perps/submitConditionalOrders" },
        { text: "cancelConditionalOrder", link: "/typescript/actions/perps/cancelConditionalOrder" },
        { text: "setReferral", link: "/typescript/actions/perps/setReferral" },
        { text: "setFeeShareRatio", link: "/typescript/actions/perps/setFeeShareRatio" },
        { text: "vaultAddLiquidity", link: "/typescript/actions/perps/vaultAddLiquidity" },
        { text: "vaultRemoveLiquidity", link: "/typescript/actions/perps/vaultRemoveLiquidity" },
      ],
    },
    {
      text: "Actions: Gateway",
      collapsed: true,
      items: [
        { text: "getWithdrawalFee", link: "/typescript/actions/gateway/getWithdrawalFee" },
        { text: "transferRemote", link: "/typescript/actions/gateway/transferRemote" },
      ],
    },
    {
      text: "Actions: Indexer",
      collapsed: true,
      items: [
        { text: "queryIndexer", link: "/typescript/actions/indexer/queryIndexer" },
        { text: "queryBlock", link: "/typescript/actions/indexer/queryBlock" },
        { text: "searchTxs", link: "/typescript/actions/indexer/searchTxs" },
        { text: "blockSubscription", link: "/typescript/actions/indexer/blockSubscription" },
        { text: "accountSubscription", link: "/typescript/actions/indexer/accountSubscription" },
        { text: "candlesSubscription", link: "/typescript/actions/indexer/candlesSubscription" },
        { text: "eventsSubscription", link: "/typescript/actions/indexer/eventsSubscription" },
        { text: "eventsByAddressesSubscription", link: "/typescript/actions/indexer/eventsByAddressesSubscription" },
        { text: "transferSubscription", link: "/typescript/actions/indexer/transferSubscription" },
        { text: "tradesSubscription", link: "/typescript/actions/indexer/tradesSubscription" },
        { text: "perpsCandlesSubscription", link: "/typescript/actions/indexer/perpsCandlesSubscription" },
        { text: "perpsTradesSubscription", link: "/typescript/actions/indexer/perpsTradesSubscription" },
        { text: "queryAppSubscription", link: "/typescript/actions/indexer/queryAppSubscription" },
        { text: "allPairStatsSubscription", link: "/typescript/actions/indexer/allPairStatsSubscription" },
        { text: "allPerpsPairStatsSubscription", link: "/typescript/actions/indexer/allPerpsPairStatsSubscription" },
      ],
    },
    {
      text: "Actions: Oracle",
      collapsed: true,
      items: [
        { text: "getPrices", link: "/typescript/actions/oracle/getPrices" },
      ],
    },
    {
      text: "Actions: Hyperlane",
      collapsed: true,
      items: [
        { text: "Addr32", link: "/typescript/actions/hyperlane/Addr32" },
        { text: "Message", link: "/typescript/actions/hyperlane/Message" },
        { text: "TokenMessage", link: "/typescript/actions/hyperlane/TokenMessage" },
        { text: "Metadata", link: "/typescript/actions/hyperlane/Metadata" },
        { text: "IncrementalMerkleTree", link: "/typescript/actions/hyperlane/IncrementalMerkleTree" },
      ],
    },
    {
      text: "Types",
      collapsed: true,
      items: [
        { text: "Address", link: "/typescript/types/Address" },
        { text: "Coin", link: "/typescript/types/Coin" },
        { text: "Coins", link: "/typescript/types/Coins" },
        { text: "Denom", link: "/typescript/types/Denom" },
        { text: "Funds", link: "/typescript/types/Funds" },
        { text: "Chain", link: "/typescript/types/Chain" },
        { text: "Account", link: "/typescript/types/Account" },
        { text: "AccountInfo", link: "/typescript/types/AccountInfo" },
        { text: "AccountDetails", link: "/typescript/types/AccountDetails" },
        { text: "User", link: "/typescript/types/User" },
        { text: "Key", link: "/typescript/types/Key" },
        { text: "KeyHash", link: "/typescript/types/KeyHash" },
        { text: "PublicKey", link: "/typescript/types/PublicKey" },
        { text: "Tx", link: "/typescript/types/Tx" },
        { text: "Message", link: "/typescript/types/Message" },
        { text: "Signer", link: "/typescript/types/Signer" },
        { text: "Signature", link: "/typescript/types/Signature" },
        { text: "Credential", link: "/typescript/types/Credential" },
        { text: "SigningSession", link: "/typescript/types/SigningSession" },
        { text: "AppConfig", link: "/typescript/types/AppConfig" },
        { text: "ChainConfig", link: "/typescript/types/ChainConfig" },
        { text: "ContractInfo", link: "/typescript/types/ContractInfo" },
        { text: "BlockInfo", link: "/typescript/types/BlockInfo" },
        { text: "IndexedBlock", link: "/typescript/types/IndexedBlock" },
        { text: "Price", link: "/typescript/types/Price" },
        { text: "Candle", link: "/typescript/types/Candle" },
        { text: "PerpsCandle", link: "/typescript/types/PerpsCandle" },
        { text: "Trade", link: "/typescript/types/Trade" },
        { text: "PerpsTrade", link: "/typescript/types/PerpsTrade" },
        { text: "PerpsEvent", link: "/typescript/types/PerpsEvent" },
        { text: "PairId", link: "/typescript/types/PairId" },
        { text: "PairParams", link: "/typescript/types/PairParams" },
        { text: "PairUpdate", link: "/typescript/types/PairUpdate" },
        { text: "PairStats", link: "/typescript/types/PairStats" },
        { text: "PerpsPairStats", link: "/typescript/types/PerpsPairStats" },
        { text: "OrderId", link: "/typescript/types/OrderId" },
        { text: "PerpsUserState", link: "/typescript/types/PerpsUserState" },
        { text: "PerpsUserStateExtended", link: "/typescript/types/PerpsUserStateExtended" },
        { text: "PerpsPairParam", link: "/typescript/types/PerpsPairParam" },
        { text: "PerpsParam", link: "/typescript/types/PerpsParam" },
        { text: "PerpsOrderKind", link: "/typescript/types/PerpsOrderKind" },
        { text: "Hex", link: "/typescript/types/Hex" },
        { text: "Base64", link: "/typescript/types/Base64" },
      ],
    },
    {
      text: "Errors",
      collapsed: true,
      items: [
        { text: "BaseError", link: "/typescript/errors/BaseError" },
        { text: "HttpRequestError", link: "/typescript/errors/HttpRequestError" },
        { text: "TimeoutError", link: "/typescript/errors/TimeoutError" },
        { text: "UrlRequiredError", link: "/typescript/errors/UrlRequiredError" },
      ],
    },
      ],
    },
  ];
}

function pythonSidebar() {
  const exchangeMethods = [
    "add_liquidity",
    "batch_update_orders",
    "cancel_conditional_order",
    "cancel_order",
    "deposit_margin",
    "liquidate",
    "remove_liquidity",
    "set_referral",
    "submit_conditional_order",
    "submit_limit_order",
    "submit_market_order",
    "submit_order",
    "withdraw_margin",
  ].map((n) => ({ text: n, link: `/python/api/methods/exchange/${n}` }));
  const infoMethods = [
    "all_perps_pair_stats",
    "broadcast_tx_sync",
    "disconnect_websocket",
    "liquidity_depth",
    "order",
    "orders_by_user",
    "pair_param",
    "pair_params",
    "pair_state",
    "pair_states",
    "perps_candles",
    "perps_events",
    "perps_events_all",
    "perps_pair_stats",
    "perps_param",
    "perps_state",
    "query_app",
    "query_app_multi",
    "query_app_smart",
    "query_status",
    "simulate",
    "subscribe_block",
    "subscribe_perps_candles",
    "subscribe_perps_trades",
    "subscribe_query_app",
    "subscribe_user_events",
    "unsubscribe",
    "user_state",
    "user_state_extended",
    "volume",
  ].map((n) => ({ text: n, link: `/python/api/methods/info/${n}` }));
  const wsMethods = ["run", "stop", "subscribe", "unsubscribe"].map((n) => ({
    text: n,
    link: `/python/api/methods/websocket-manager/${n}`,
  }));
  const hlCompatExchange = [
    "bulk_cancel",
    "bulk_cancel_by_cloid",
    "bulk_modify_orders_new",
    "bulk_orders",
    "cancel",
    "cancel_by_cloid",
    "market_close",
    "market_open",
    "modify_order",
    "order",
    "set_expires_after",
    "set_referrer",
  ].map((n) => ({ text: n, link: `/python/migration/hl-compat/exchange/${n}` }));
  const hlCompatInfo = [
    "all_mids",
    "candles_snapshot",
    "disconnect_websocket",
    "historical_orders",
    "l2_snapshot",
    "meta",
    "meta_and_asset_ctxs",
    "name_to_asset",
    "name_to_pair",
    "open_orders",
    "query_order_by_oid",
    "subscribe",
    "unsubscribe",
    "user_fills",
    "user_fills_by_time",
    "user_state",
  ].map((n) => ({ text: n, link: `/python/migration/hl-compat/info/${n}` }));
  const typeNames = [
    "Addr",
    "AllForPair",
    "Block",
    "CancelAction",
    "CandleInterval",
    "ClientOrderId",
    "ClientOrderIdRef",
    "ConditionalOrderRef",
    "Connection",
    "Hash256",
    "OrderId",
    "OrderRemoved",
    "PageInfo",
    "PairId",
    "PairParam",
    "PairState",
    "Param",
    "PerpsCandle",
    "PerpsEvent",
    "PerpsEventSortBy",
    "PerpsPairStats",
    "Position",
    "PositionExtended",
    "QueryOrderResponse",
    "QueryOrdersByUserResponseItem",
    "ReasonForOrderRemoval",
    "SignDoc",
    "State",
    "SubmitAction",
    "TimeInForce",
    "Trade",
    "TriggerDirection",
    "Tx",
    "UnsignedTx",
    "UserState",
    "UserStateExtended",
  ].map((n) => ({ text: n, link: `/python/api/types/${n}` }));

  return [
    {
      text: "Getting Started",
      items: [
        { text: "Installation", link: "/python/getting-started/installation" },
        { text: "First Call", link: "/python/getting-started/first-call" },
        { text: "Project Setup", link: "/python/getting-started/project-setup" },
      ],
    },
    {
      text: "Concepts",
      collapsed: true,
      items: [
        { text: "Clients", link: "/python/concepts/clients" },
        { text: "Signers", link: "/python/concepts/signers" },
        { text: "Transactions", link: "/python/concepts/transactions" },
        { text: "Subscriptions", link: "/python/concepts/subscriptions" },
        { text: "Encoding & Types", link: "/python/concepts/encoding-and-types" },
        { text: "Error Handling", link: "/python/concepts/error-handling" },
        { text: "Rate Limits & Quotas", link: "/python/concepts/rate-limits" },
      ],
    },
    {
      text: "API Reference",
      items: [
        {
          text: "Classes",
          items: [
            { text: "API", link: "/python/api/classes/API" },
            { text: "Exchange", link: "/python/api/classes/Exchange" },
            { text: "Info", link: "/python/api/classes/Info" },
            { text: "WebsocketManager", link: "/python/api/classes/WebsocketManager" },
            { text: "Secp256k1Wallet", link: "/python/api/classes/Secp256k1Wallet" },
            { text: "SingleSigner", link: "/python/api/classes/SingleSigner" },
          ],
        },
        { text: "Exchange methods", collapsed: true, items: exchangeMethods },
        { text: "Info methods", collapsed: true, items: infoMethods },
        { text: "WebsocketManager methods", collapsed: true, items: wsMethods },
        {
          text: "Functions",
          items: [
            { text: "dango_decimal", link: "/python/api/functions/dango_decimal" },
            { text: "paginate_all", link: "/python/api/functions/paginate_all" },
            {
              text: "sign_doc_canonical_json",
              link: "/python/api/functions/sign_doc_canonical_json",
            },
            { text: "sign_doc_sha256", link: "/python/api/functions/sign_doc_sha256" },
          ],
        },
        { text: "Types", collapsed: true, items: typeNames },
        {
          text: "Errors",
          items: [
            { text: "Error", link: "/python/api/errors/Error" },
            { text: "ClientError", link: "/python/api/errors/ClientError" },
            { text: "ServerError", link: "/python/api/errors/ServerError" },
            { text: "GraphQLError", link: "/python/api/errors/GraphQLError" },
            { text: "TxFailed", link: "/python/api/errors/TxFailed" },
          ],
        },
      ],
    },
    {
      text: "Migration",
      items: [
        { text: "Hyperliquid SDK", link: "/python/migration/hyperliquid" },
        { text: "Missing methods", link: "/python/migration/missing-methods" },
        { text: "HL-compat: Exchange", collapsed: true, items: hlCompatExchange },
        { text: "HL-compat: Info", collapsed: true, items: hlCompatInfo },
      ],
    },
  ];
}

function rustSidebar() {
  return [
    {
      text: "Getting Started",
      items: [
        { text: "Installation", link: "/rust/getting-started/installation" },
        { text: "First Call", link: "/rust/getting-started/first-call" },
        { text: "Project Setup", link: "/rust/getting-started/project-setup" },
      ],
    },
    {
      text: "Concepts",
      collapsed: true,
      items: [
        { text: "Clients", link: "/rust/concepts/clients" },
        { text: "Signers & Authentication", link: "/rust/concepts/signers-and-authentication" },
        { text: "Transactions", link: "/rust/concepts/transactions" },
        { text: "Subscriptions", link: "/rust/concepts/subscriptions" },
        { text: "Encoding & Types", link: "/rust/concepts/encoding-and-types" },
        { text: "Error Handling", link: "/rust/concepts/error-handling" },
        { text: "Rate Limits & Quotas", link: "/rust/concepts/rate-limits" },
      ],
    },
    {
      text: "API Reference",
      items: [
        {
          text: "Clients",
          items: [
            { text: "HttpClient", link: "/rust/api/clients/HttpClient" },
            { text: "WsClient", link: "/rust/api/clients/WsClient" },
            { text: "Session", link: "/rust/api/clients/Session" },
            { text: "SingleSigner", link: "/rust/api/clients/SingleSigner" },
            { text: "Keystore", link: "/rust/api/clients/Keystore" },
          ],
        },
        {
          text: "HttpClient methods",
          items: [
            { text: "paginate_all", link: "/rust/api/methods/http-client/paginate_all" },
            { text: "paginate_accounts", link: "/rust/api/methods/http-client/paginate_accounts" },
            { text: "paginate_transfers", link: "/rust/api/methods/http-client/paginate_transfers" },
            { text: "paginate_transactions", link: "/rust/api/methods/http-client/paginate_transactions" },
            { text: "paginate_blocks", link: "/rust/api/methods/http-client/paginate_blocks" },
            { text: "paginate_events", link: "/rust/api/methods/http-client/paginate_events" },
            { text: "paginate_messages", link: "/rust/api/methods/http-client/paginate_messages" },
            { text: "query_app", link: "/rust/api/methods/http-client/query_app" },
            { text: "query_store", link: "/rust/api/methods/http-client/query_store" },
            { text: "simulate", link: "/rust/api/methods/http-client/simulate" },
            { text: "query_block", link: "/rust/api/methods/http-client/query_block" },
            { text: "query_block_outcome", link: "/rust/api/methods/http-client/query_block_outcome" },
            { text: "broadcast_tx", link: "/rust/api/methods/http-client/broadcast_tx" },
            { text: "search_tx", link: "/rust/api/methods/http-client/search_tx" },
          ],
        },
        {
          text: "WsClient methods",
          items: [
            { text: "new", link: "/rust/api/methods/ws-client/new" },
            { text: "from_http_url", link: "/rust/api/methods/ws-client/from_http_url" },
            { text: "connect", link: "/rust/api/methods/ws-client/connect" },
            { text: "subscribe", link: "/rust/api/methods/ws-client/subscribe" },
          ],
        },
        {
          text: "Session methods",
          items: [
            { text: "subscribe", link: "/rust/api/methods/session/subscribe" },
          ],
        },
        {
          text: "SingleSigner methods",
          items: [
            { text: "new", link: "/rust/api/methods/single-signer/new" },
            { text: "new_first_address_available", link: "/rust/api/methods/single-signer/new_first_address_available" },
            { text: "with_user_index", link: "/rust/api/methods/single-signer/with_user_index" },
            { text: "with_query_user_index", link: "/rust/api/methods/single-signer/with_query_user_index" },
            { text: "with_nonce", link: "/rust/api/methods/single-signer/with_nonce" },
            { text: "with_query_nonce", link: "/rust/api/methods/single-signer/with_query_nonce" },
            { text: "query_user_index", link: "/rust/api/methods/single-signer/query_user_index" },
            { text: "query_next_nonce", link: "/rust/api/methods/single-signer/query_next_nonce" },
            { text: "unsigned_transaction", link: "/rust/api/methods/single-signer/unsigned_transaction" },
            { text: "sign_transaction", link: "/rust/api/methods/single-signer/sign_transaction" },
            { text: "query_nonce", link: "/rust/api/methods/single-signer/query_nonce" },
            { text: "update_nonce", link: "/rust/api/methods/single-signer/update_nonce" },
          ],
        },
        {
          text: "Keystore methods",
          items: [
            { text: "from_file", link: "/rust/api/methods/keystore/from_file" },
            { text: "write_to_file", link: "/rust/api/methods/keystore/write_to_file" },
          ],
        },
        {
          text: "Subscriptions",
          items: [
            { text: "SubscriptionVariables", link: "/rust/api/subscriptions/SubscriptionVariables" },
            { text: "SubscriptionStream", link: "/rust/api/subscriptions/SubscriptionStream" },
          ],
        },
        {
          text: "Traits",
          items: [
            { text: "Secret", link: "/rust/api/traits/Secret" },
          ],
        },
        {
          text: "Types",
          items: [
            { text: "PageInfo", link: "/rust/api/types/PageInfo" },
          ],
        },
        {
          text: "Errors",
          items: [
            { text: "WsError", link: "/rust/api/errors/WsError" },
          ],
        },
      ],
    },
  ];
}
