COMETBFT_VERSION := "0.38.19"

build:
  docker buildx build \
    --push \
    --platform linux/arm64,linux/amd64 \
    --build-arg COMETBFT_GIT_TAG=v{{COMETBFT_VERSION}} \
    --tag ghcr.io/leftcurve/cometbft:{{COMETBFT_VERSION}} \
    .
