# Based on:
# https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions

name: Book

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/book.yaml
      - book/**
      - book.toml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      pages: write    # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        run: rustup default stable

      # This builds mdbook from source, which is really slow.
      # We should consider using: https://github.com/peaceiris/actions-mdbook
      # but it doesn't support the katex preprocessor.
      #
      # 20251124: mdbook 0.5 is released, but mdbook-katex won't support it:
      # https://github.com/lzanini/mdbook-katex/issues/130
      # It's a shame, because 0.5 comes with a bunch of nice new features.
      # For now, let's just pin mdbook to 0.4. At a later time we can migrate to
      # another LaTeX renderer e.g. MathJax.
      - name: Install mdbook and preprocessors
        run: cargo install mdbook@0.4.48 mdbook-katex@0.9.4

      - name: Build book
        run: mdbook build

      - name: Create CNAME file
        run: echo "docs.dango.exchange" > ./target/book/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: ./target/book/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
